### ISSUE TITLE
"Unable to process a message" does not say which one

### ISSUE THREAD

**Issue by forki** [elmish/elmish#132]
### Description

"Unable to process a message" does not say which one

### Repro code

forget to handle message in update

**Comment by et1975** [comment]
Hmm, in light of @alfonsogarciacaro's  "mb.Post is synchronous (except at mod 2000 intervals)" I'm thinking I have to rewrite the dispatch it into a loop to guarantee the FIFO order of messages. Might address this as part of the rewrite.

**Comment by forki** [comment]
Awesome. Thank you.
I know it's always a fuck up on my side when this message is seen, but I
wish it would be more helpful ;-)

Am 01.02.2018 20:49 schrieb "Eugene Tolmachev" <notifications@github.com>:

Hmm, in light of @alfonsogarciacaro <https://github.com/alfonsogarciacaro>'s
"mb.Post is synchronous (except at mod 2000 intervals)" I'm thinking I have
to rewrite the dispatch it into a loop to guarantee the FIFO order of
messages. Might address this as part of the rewrite.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/fable-elmish/elmish/issues/132#issuecomment-362381440>,
or mute the thread

**Comment by MangelMaxime** [comment]
I made a proposition in this direction in the Fable compiler repo: https://github.com/fable-compiler/Fable/issues/1389

**Comment by et1975** [comment]
@forki can you give 3,0 beta a spin? It should report the msg causing an error.

**Comment by forki** [comment]
Cool. Will update asap

Am So., 9. Dez. 2018, 01:46 hat Eugene Tolmachev <notifications@github.com>
geschrieben:
