### ISSUE TITLE
fable-elmish --> elmish?

### ISSUE THREAD

**Issue by dsyme** [elmish/elmish#145]
Hi fable-elmish 

Would it be possible to rename "fable-elmish" to "elmish".  There are a few of us working on Elmish.WPF, Elmish.XamarinForms and so on and these are Elmish models independent of Fable.

Diego Esmerio grabbed the domain https://github.com/elmish to prevent it being taken, and we can coordinate with him to do delete then a rename

**Comment by et1975** [comment]
heads up @alfonsogarciacaro @MangelMaxime @Zaid-Ajaj

**Comment by forki** [comment]
I think it would make sense.

**Comment by MangelMaxime** [comment]
I think this is a good idea.

The name `Fable.Elmish` is because originally Fable needed the `Fable.` prefix on package to use them.

**Comment by MangelMaxime** [comment]
When the org has been moved we also need to edit:

- [Awesome Fable](https://github.com/kunjee17/awesome-fable/)
- This page http://fable.io/samples-browser/, @alfonsogarciacaro I don't find the file who generate this page can you help ?

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime It's a different repo :) Here: https://github.com/fable-compiler/samples-browser

BTW, we should probably add links to elmish site in fable.io front page and docs.

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro I know it's a different repo but can't find the .md file to modify :)

I only see the "compressed" html generated from invoking "react server side".

**Comment by MangelMaxime** [comment]
I don't think we should publish docs with 2.0-beta changes because by default users are using Elmish 1.0 and we are still not sure when or if we are going to release this changes.

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime Ah, sorry. That part is actually generated in the fable-compiler.github.io repo directly from F# code. [This line specifically](https://github.com/fable-compiler/fable-compiler.github.io/blob/a0a17cb1f0027f957f71f3f18c291ef53178e34a/src/components/SamplesPage.fs#L21) (it's a string literal but uses MD format for the links).

**Comment by et1975** [comment]
`v1.x` is now the default branch and the docs are published from it.
