### ISSUE TITLE
Add an integrated Elmish example including handle DB, ACL and so on, thanks.

### ISSUE THREAD

**Issue by ScottHuangZL** [elmish/elmish#147]
### Description

Current example mainly try to demo the UI. 
As for an integrated example, it will need handle **DB, ACL, session, JWT** and so on.
Would like an official example to include both frontend and backend code even it is basic, thanks.

### Repro code

Please provide the F# code to reproduce the problem.
Ideally, it should be possibe to easily turn this code into a unit test.

### Expected and actual results

Please provide the expected and actual results.

### Related information 

* elmish version:
* fable-compiler version:
* fable-core version:
* Operating system:

**Comment by et1975** [comment]
Please see https://safe-stack.github.io/ for the full-stack example.
