### ISSUE TITLE
Question on how to produce a command

### ISSUE THREAD

**Issue by thitemple** [elmish/elmish#150]
### Description

Hi, I'm coming from Elm and trying to access the current location from the user a transform it into a Cmd a having difficulties doing so.

I'd like that when I run the following code either a message with the position would be created or Cmd.none, is there a way to do so? Am I doing this wrong?
Thanks

```
let getCurrentPosition : Cmd<Msg> =
    navigator.geolocation.getCurrentPosition (
        (fun pos -> console.log(pos)), 
        (fun _ -> console.error("")))
```

**Comment by MangelMaxime** [comment]
You should wrap it in a promise:

- [Wrap the API in a nice promise](https://github.com/MangelMaxime/NDC_Oslo_2018/blob/master/demo/src/Demos/geolocation.js)
- [Import custom function](https://github.com/MangelMaxime/NDC_Oslo_2018/blob/master/demo/src/Soluce/MapDemoSoluce.fs#L15)
- [Promise call](https://github.com/MangelMaxime/NDC_Oslo_2018/blob/master/demo/src/Soluce/MapDemoSoluce.fs#L33)

**Comment by Zaid-Ajaj** [comment]
@MangelMaxime your solution is very clean but it requires adding stuff in different places and js interop, an alternative "F# only" solution is to make a command in-line, remember that a `Cmd<'Msg>` is just `('Msg -> unit) list` 
```fs
type Msg = RecievedCurrentPosition of Postion

let getCurrentPosition() : Cmd<Msg> = 
  [ fun dispatch -> 
       navigator.geolocation.getCurrentPosition(
         (fun pos -> dispatch (RecievedCurrentPosition pos)), 
         (fun _ -> ())) ] 
``` 
Notice that we are ignoring the error if it occurs. To propagate the error data, change your message type to encode errors as well: 
```fs
// assuming the resulting error is an actual exception
type Msg = RecievedCurrentPosition of Result<Position, exn> 

let getCurrentPosition() : Cmd<Msg> = 
  [ fun dispatch -> 
       navigator.geolocation.getCurrentPosition(
         (fun pos -> dispatch (RecievedCurrentPosition (Ok pos))), 
         (fun ex ->  dispatch (RecievedCurrentPosition (Error ex)))) ] 
```

**Comment by MangelMaxime** [comment]
@Zaid-Ajaj You are right indeed. :)

I prefer to encourage the usage of promise when possible because you can easily chain them. Chaining commands is less straight forward, and perform one more update call per step.

**Comment by Zaid-Ajaj** [comment]
@MangelMaxime That is a very good point, I haven't thought about that. `Cmd.map` can in fact very confusing at first sight

**Comment by thitemple** [comment]
Thanks, I decided to go with the F# only simpler approach, but I understand your reasoning @MangelMaxime.

So a `Cmd<'a>` can be a list of functions that get called with the dispatcher as the argument, is that it?

**Comment by MangelMaxime** [comment]
The "F# only" approach isn't really simpler because the implementation of the `Command` is a detail and can be change in the future.

For the implementation yes, you have the definition [here](https://github.com/elmish/elmish/blob/v1.x/src/cmd.fs#L15-L19).

**Comment by et1975** [comment]
I don't see `list` being a relevant detail in this case, but if you need a list you can always use 

```fsharp 
Cmd.batch [ Cmd.ofFunc ...; Cmd.attemptFunc ...; etc ]
```

**Comment by MangelMaxime** [comment]
I guess he was refering to how Commands are implementing under the hood.

**Comment by MangelMaxime** [comment]
We can also avoid creating a custom commands and still use F# only solution using subscriber.

```fs
type Model =
    { Position : Browser.Position option
      ErrorMessage : string }

type Msg =
    | GetPosition
    | GetPositionSuccess of Browser.Position
    | GetPositionError of Browser.PositionError

module Sub =
    // Subscriber used to reach gealocation API
    let getPosition onSuccess onError dispatch =
        Browser.navigator.geolocation.getCurrentPosition(
          onSuccess >> dispatch,
          onError >> dispatch
        )

let update (msg:Msg) (model:Model) =
    match msg with
    | GetPosition ->
        model, Cmd.ofSub (Sub.getPosition GetPositionSuccess GetPositionError)
    
    | GetPositionSuccess posision ->
        { model with Position = Some position
                     ErrorMessage = "" }, Cmd.none
    
    | GetPositionError error ->
        { model with Position = None
                     ErrorMessage = error.message }, Cmd.none
```
