### ISSUE TITLE
Add Cmd.ofTask

### ISSUE THREAD

**Issue by forki** [elmish/elmish#158]
For dotnet core programs I'd like to use Cmd.ofTask. It's easy to do it myself by using Async.AwaitTask and Cmd.ofAsync, but it would be nice to have it ootb

**Comment by et1975** [comment]
Easy enough 👍

**Comment by et1975** [comment]
I'm sure it is, for some reason I assumed that would be desirable :/

**Comment by et1975** [comment]
Released the async version as 2.0.3.
