### ISSUE TITLE
Fable Community Heroes 2018

### ISSUE THREAD

**Issue by alfonsogarciacaro** [elmish/elmish#159]
Congratulations @et1975! [You've been nominated Fable Community Hero 2018](https://twitter.com/FableCompiler/status/1056877423864745984) with the biggest number of votes. If you want to have your well deserved Fable backpack, just send me the address you want me to send it to at alfonso.garcia-caro (at) outlook.com.

Thanks a lot for all your contributions!

**Comment by et1975** [comment]
Thank you, I'm flattered, although personally I've voted for @Zaid-Ajaj who I think has done a lot more  for the community in 2018.
