### ISSUE TITLE
Remove Fable.PowerPack dependency

### ISSUE THREAD

**Issue by alfonsogarciacaro** [elmish/elmish#161]
As discussed [here](https://github.com/fable-compiler/fable-powerpack/issues/63), Fable.PowerPack will be split in multiple packages. [Fable.Promise](https://github.com/fable-compiler/fable-promise) has already been published, and since Elmish 3 is in beta this is a good opportunity to remove the dependency just for [this method](https://github.com/elmish/elmish/blob/2efc99c70053b5aec9a20e34c262050be6674642/src/cmd.fs#L98-L107) (yes, I remember it was me who convinced you to add the dependency 😅). 

There are two options:

- Replace the Fable.PowerPack dependency with the new Fable.Promise.
- Don't use any dependency at all and just emit the JS code directly.

> Note that `Promise` itself is a type in the `Fable.Import.JS` namespace included in Fable.Core, so even if Elmish doesn't depend on Fable.PowerPack, users will still be able to use it in combination with `Cmd.ofPromise`.

**Comment by et1975** [comment]
I remember there was some discussion about hot/cold semantics, I think I'd prefer to use a lib so that elmish ends up with the same semantics as the rest of the Fable world, whatever they are.

**Comment by et1975** [comment]
published beta-3 w/ Fable.Promise instead of Fable.PowerPack.

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/49695933-6f935380-fba2-11e8-9e9b-d0db751a6310.png)

any ideas what this means?

**Comment by forki** [comment]
also I get:

![image](https://user-images.githubusercontent.com/57396/49695947-aff2d180-fba2-11e8-9c92-3cda2a6437b2.png)

**Comment by MangelMaxime** [comment]
Elmish beta-3 use a new implementation of the `Program<_>` so `Elmish.HMR` needs to be updated to this new implementation too, and same for `Elmish.Browser` I think etc.

**Comment by alfonsogarciacaro** [comment]
@et1975 Seems [this commit removed the FABLE_COMPILER directive](https://github.com/elmish/elmish/commit/c74a6dd40063669e14864a63dc8da803425ebe94#diff-885895d5c86ad3452c00a34a9a5fe93d) so the `Cmd.ofPromise` doesn't get it to the binary and the IDE complains. I can think of two solutions for this:

- Use two different project files for each target, this will help you easily control each package name, dependencies and compiler directives.
- To minimize the number of changes, you can just pass a property when packing (not sure how to do that with Paket, with the `dotnet pack` command you just add `/property:FableCompiler=true`) and then add the following conditional group to your project:

```xml
  <PropertyGroup Condition="'$(FableCompiler)' == 'true'">
    <DefineConstants>$(DefineConstants);FABLE_COMPILER</DefineConstants>
  </PropertyGroup>
```

> I was assuming in the second case `Cmd.ofPromise` wouldn't be included in the Elmish binary, the Fable.Promise dependency would still be there. However, looking [at the Nuget page](https://www.nuget.org/packages/Elmish/3.0.0-beta-3) the dependency doesn't seem to be there. Not sure why (does Paket/Nuget/dotnet SDK automatically detect the dependency is not being used?).

**Comment by et1975** [comment]
Released beta-4 with fable directive back in.

**Comment by alfonsogarciacaro** [comment]
Thanks! Yes, Fable adds the directive (I didn't try but I assume Fable compilation worked), but because `Cmd.ofPromise` was not in the .dll, it's the IDE what complains (not Fable).

**Comment by alfonsogarciacaro** [comment]
BTW, about the hot/cold discussion. That was only about the `promise` Computation Expression, so it doesn't affect `Cmd.ofPromise`. But you're right @et1975, it's probably better to use the dependency to make sure promises are dealt the same way across the ecosystem in case Elmish implements more promise-related helpers :+1:

**Comment by et1975** [comment]
Yes, for now in fable elmish libs it's safe to use `id`, I'll figure out
something better though.

**Comment by forki** [comment]
Cool so I only have to wait for hmr to update.

Am Mo., 10. Dez. 2018, 04:06 hat Eugene Tolmachev <notifications@github.com>
geschrieben:

**Comment by MangelMaxime** [comment]
Fable.Elmish.HMR version 4.0.0-beta-1 has been released.

**Comment by forki** [comment]
looks like elmish beta and hmr works now. yay!

**Comment by tforkmann** [comment]
I updated my client as well.

But I now get this:
![image](https://user-images.githubusercontent.com/4168951/49740231-1572bb00-fc94-11e8-8421-e039a9a4a561.png)

Its seems Encode and Decode is not defined anymore.

**Comment by forki** [comment]
I think you need to patch everything to 3.x prerelease

**Comment by tforkmann** [comment]
Ok, that worked!
Thanks!

**Comment by forki** [comment]
except there is no beta version of fable.elmish.debugger ;-(

/cc @MangelMaxime

**Comment by et1975** [comment]
I don't know if you really need one, as debugger doesn't change types of the program and simply updates the existing instance. I can publish it though if you have a problem with the 2.0 debugger working with 3.0 elmish.

**Comment by forki** [comment]
thanks!

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/49809012-2556d180-fd5e-11e8-91c0-26d6652cdcba.png)

there is still something odd.

**Comment by et1975** [comment]
Yep, dependencies were not referenced. Published beta-2.
