### ISSUE TITLE
To add the exit criteria or not

### ISSUE THREAD

**Issue by et1975** [elmish/elmish#162]
cc @alfonsogarciacaro @MangelMaxime @Zaid-Ajaj @cmeeren 

I'm thinking to extend `Program` with an exit criteria. It would be just a predicate that tests for a specific value of '`msg',  i.e. `'msg -> bool' and be invoked by the dispatch loop to determine if it needs to exit. What do you guys think?

**Comment by cmeeren** [comment]
I feel I'm lacking context and more details. In which situations is it helpful to control the exit of a loop? And have you considered other methods of exiting a loop?

**Comment by et1975** [comment]
AFAIK currently there's no graceful way to stop the loop in JS. A typical SPA doesn't need to stop, but something that runs multiple instances of `Program`, or is running as an agent under node might benefit from this.
On .NET side terminating the process is possible of course, but that's a nuclear option when one might simply want to restart the loop at later time, maybe with different parameters.
Not that I have an immediate need for this, I just thought since we are already making changes as part of 3.0 I could put this in as well, but if the feeling is "no thanks" then that's ok too.

**Comment by cmeeren** [comment]
I don't care much either way.

If implemented, extending `Program` with a `'msg -> bool` property seems like a good option. It means users can easily stop a loop from within the loop itself.

Another option, as @Nhowka suggests, is to provide a `unit -> unit` somewhere that users can call if needed, but I don't immediately see how this can easily be called for a specific `Program` instance/loop since the `Program` instance usually defined at the end of the compilation order and not available in the core Elmish logic.

**Comment by Nhowka** [comment]
A way would be via a `ref`. Something like:

```fs
let killSwitch = ref ignore

Program.mkProgram init update view
|> Program.withKillSwitch killSwitch
|> Program.run
```

And then `!killSwitch ()` could be called.

**Comment by cmeeren** [comment]
Yes, you'd need to rely on mutable state (though more or less official F# guidelines, such as "Expert F#", favor `mutable` instead of `ref`). Not particularly dangerous in this case, but I still like the message based approach a bit better.

**Comment by MangelMaxime** [comment]
This remember me of an old issue I opened https://github.com/elmish/react/issues/3

And I guess if we had this feature at the time, then canceling a elmish program would have been possible by default without the need to re-implement the `withReact` function.

**Comment by alfonsogarciacaro** [comment]
Not directly related to the issue but I'm concerned every change to the `Program` type requires updating all Elmish-related libraries. Although it's not the most elegant solution, in these cases I usually add an untyped dictionary (like `Map<string, obj>`) in a field named `Extra` or similar so adding new features doesn't require changing all dependencies (when the feature becomes "standard" it can be added as a typed field in the next major version). In this case you could add a `'Model->bool` function to decide if the loop must stop, then Elmish can detect if this function is present in the `Extra` dictionary and run it after each loop iteration.

**Comment by cmeeren** [comment]
> I'm concerned every change to the `Program` type requires updating all Elmish-related libraries

Wouldn't it only require updating all libraries that are instantiating a brand new `Program` instance themselves? Elmish.WPF certainly don't (and thus wouldn't be affected by this change). Elmish.WPF only changes an existing `Program` instance using the copy-and-update syntax (`{ program with ... }`).

**Comment by et1975** [comment]
>  every change to the Program type requires updating all Elmish-related libraries

Only libraries that directly create new instances of `Program`, but yes, I'd like to remove the need for that as well. Ideally the `Program` type will become opaque and just offer functions to work with it, I need to try it, but maybe we can simply replace existing record instantiations with `Program.mkProgram` and augment the result as needed.

**Comment by kspeakman** [comment]
@MangelMaxime So far yours seems to be the main use case. Is this something you would use if implemented? What would be ideal dev experience for stopping the event loop for your case? (A couple of options were mentioned.)

**Comment by TimLariviere** [comment]
I'm currently porting Fabulous to Elmish as the update loop was mostly just a different implementation of the same thing.

All is working great, except for this issue.

Fabulous has a tool called LiveUpdate (which gave birth to https://github.com/fsprojects/FSharp.Compiler.PortaCode)

This tool detects changes made to `.fs` files and recompiles the code before sending it to the running application (Android, iOS, etc.)
The `Program<'arg, 'model, 'msg, 'view>` is then hot replaced by the newly compiled one.

But for the moment, I can only start a new loop (which makes LiveUpdate works) and I can't free any resource taken by the previous loop.

Any plan to implement this feature?

**Comment by et1975** [comment]
Yes, I'd still like to have this. Maybe in addition to the predicate we'd add:
* to `Program` type: `onTermination: unit->unit`
* to `Program` module: `withTermination: (unit->unit)->Program->Program`

would that be enough @MangelMaxime @TimLariviere ?

**Comment by MangelMaxime** [comment]
I guess so my question is how would we trigger a `Termination`?

I suspect this is a case by case depending on the use case. So I am just asking for an example. ^^

Is it by sending an event? 

Is there a function that should be called from a "mapping" function?

For example, in `Elmish.HMR` could take advantage of this `exit` criteria. Right now, we are marking the old program `Inactive` and stop updating them. [Source](https://github.com/elmish/hmr/blob/master/src/hmr.fs#L85-L87)

What would we have to do to support the exit system?

**Comment by et1975** [comment]
HMR already wraps the program with it's own `'msg` type, so that's great. To support the termination you'd need to provide:
* the predicate: `'msg -> bool` that tells the dispatch loop that it needs to terminate
* the termination function: tentatively `unit->unit` that does the cleanup, if any.

The tricky part is the current loop implementation, which is just a callback, so it has no way to truly exit - only ignore any future messages. That and the cleanup of the subscriptions, which will keep firing and hog the resources. Not sure how Fabulous and HMR currently deals with those, but I'm open to suggestions on how to release those properly even if we break the current API.

**Comment by MangelMaxime** [comment]
> That and the cleanup of the subscriptions, which will keep firing and hog the resources. Not sure how Fabulous and HMR currently deals with those, but I'm open to suggestions on how to release those properly even if we break the current API.

Well, currently HMR is it ignores the new messages. [Source](https://github.com/elmish/hmr/blob/master/src/hmr.fs#L80).

The resource is still being used. They have the same problem in React world where if the user is implementing HMR support to its component then it's the user job to dispose of the resource when it detects the HMR call.
But currently, we don't have a list of resource used by the user or Elmish application so I can't free it for them.

This is for this reason that if a user registers a listener to a JavaScript event (custom events). Then after an HMR call, the listener will appear to "not work". Because the listener is still sending the Msg to the previous `dispatch` instance.

**Comment by TimLariviere** [comment]
Fabulous uses an intermediate `ProgramDispatch` type to hold a static reference to the dispatch function and act like a Singleton. ([Source](https://github.com/fsprojects/Fabulous/blob/ed521b7671e3ff1689f739fc81bd9056e2c55bc4/src/Fabulous.Core/ElmishProgram.fs#L17-L25))
Whenever a new Program is started, this static reference is replaced by the new dispatch (which calls its corresponding `processMsg`)

So we don't really need to clean up the subscriptions. They will keep firing but their messages will be processed by the new Program.

The downside is that only one Program in parallel is possible.

**Comment by et1975** [comment]
@MangelMaxime @TimLariviere I pushed what I had in mind to my fork, let me know if it makes sense for you and does what you need.

**Comment by MangelMaxime** [comment]
@et1975 It seems good to me. 👍 

The only strange thing is you wrote `alfa` instead of `alpha` :)

On a side note, I will need the alpha version in order to update `Fable.HMR` and make it match the new `runWith` signature.

**Comment by et1975** [comment]
Released as v4 alpha-1.

**Comment by alfonsogarciacaro** [comment]
@et1975 Sorry, I haven't been following v4 development but I'm very interested in have termination capabilities for Elmish. But I appreciate Elmish has become a dependency of many libraries and it's increasingly difficult to make breaking changes (v4 has been in alpha for a couple of years now).

Would it be possible to release the termination capabilities in a minor release without breaking changes? It's a pity that `Program` fields are private but adding a new one still becomes a breaking change because of the `map` function, so it'd be nice to keep the signature as is and add `mapTermination` as its own function (like `mapErrorHandler`). `map` could even be marked as Obsolete and make separate `mapXXX` helpers available.

> Another solution would be to have `.Map`  as a public method of Program with optional arguments. It breaks the style of the rest of the API, but the helper is supposed to be used only by library authors.

**Comment by et1975** [comment]
Generally speaking Program `map` can't be done piece-meal because something like Navigation changes the type of generic arguments, ie. anything that changes `'msg` or `'model` must change everything else that uses them.
