### ISSUE TITLE
Elmish 3.0 ?

### ISSUE THREAD

**Issue by theimowski** [elmish/elmish#163]
Are there any outstanding issues for releasing Elmish 3.0, or is it just a matter of sticking to beta phase long enough? Asking as I can see it's 2 months since the beta was published, and couldn't find any relevant open issues

**Comment by et1975** [comment]
I thought to wait for #162, but I'm not happy with the results yet.

**Comment by et1975** [comment]
Potential deliverables and blockers before we go stable:
- New dispatch loop. Pretty sure it's good to be released, but I can't make the [performance tests](/et1975/react-fable-elm-performance-comparison) work using the beta elmish... it could be unrelated to the dispatch loop changes, but would be nice to understand the cause. 
- Making the `Program` type opaque. I've got it implemented, but not sure if it's worth pursuing: `Program.map` that we'd use in `toNavigable` and `withHMR` to change the type needs pretty much all the same inputs as constructing the new record and will be just as unstable as dealing with the record. I'm not interested in type-unsafe options, but I'm not seeing what else we can do.
- Conditional loop termination. This is trickier than expected, as there's no actual loop.

I'll push what I've got to my fork if anyone is interested in what it looks like, but as all of this is self-imposed we could release 3.0 w/o the last two to support the Fable.Core 3.

- [Elmish.React's `lazyView`](https://github.com/elmish/react/issues/14) probably needs a decision before we go stable. @alfonsogarciacaro insists that it's no longer necessary, but `memo` doesn't quite have the same ergonomics at the moment. Should we reimplement `lazy` with memo and maybe add `Named`  module with the constructors that also take `name`?

**Comment by MangelMaxime** [comment]
I am not sure if making the `Program` opaque is something worth. Because I think, that libraries which are wrapping the program will still need to be updated in order to map/call the added function. Or am I missing something?

**Comment by et1975** [comment]
Yes, the libraries that change the type parameters of the program today by constructing new instance of the record will have to change, but the goal was to minimise the impact going forward, which opaque types do accomplish - by offering functions to work with the type. My only hesitation is due to `'msg` and `'model` affecting like 80% of the record, but if we add another field tomorrow that either doesn't depend on these type parameters or that can be trivially mapped by some means then we still eliminate the impact on the libraries.

**Comment by rfrerebe** [comment]
Submitted PR #171

**Comment by et1975** [comment]
Released and pushed the docs update.
