### ISSUE TITLE
[documentation] The diagrams are not rendering on elmish.github.io

### ISSUE THREAD

**Issue by et1975** [elmish/elmish#164]
In the best traditions of the interwebs we've been referencing Elm's sequence diagrams directly and now they don't render. Need our own copy of the images, preferably in v2.x branch so that we could release updated docs for the current stable release.

**Comment by MangelMaxime** [comment]
I only have this is from one of my slides.

![image](https://user-images.githubusercontent.com/4760796/53284875-4a05f700-375a-11e9-87e6-01b9121738e6.png)

I think we will have to create them by ourself.

**Comment by et1975** [comment]
Found the sources: https://github.com/sporto/elm-tutorial/blob/master/en-v01/02-elm-arch/06-composing.pu

**Comment by et1975** [comment]
fixed in v2/gh-pages, will push the master later.
