### ISSUE TITLE
Cmd.ofMsg is gone. Why?

### ISSUE THREAD

**Issue by forki** [elmish/elmish#170]
Cmd.ofMsg is deprecated and now we have Cmd.OfFunc.result - is that really a good move?
ofMsg is widely used and reads so much better IMHO. Could you please expand on the reason?

**Comment by MangelMaxime** [comment]
You can read the discussion that leads to this changes in #166

**Comment by forki** [comment]
it doesn't really talk about ofMSg or does it?

**Comment by MangelMaxime** [comment]
It talks about all the `Cmd.*`.

Originally, the idea was to unify the API of `Cmd.ofAsync`, `Cmd.ofPromise` with `Cmd.ofFunc`.

So all three of them have:

- `either`
- `perform`
- `attempt`
- `result`

However, now that I look at the implemetation `Cmd.OfFunc.result` doesn't have the same signature as `Cmd.OfAsync.result` or `Cmd.OfPromise.result`.

Both `Cmd.OfAsync.result` and `Cmd.OfPromise.result` takes 2 arguments:

1. Something to execute
2. The message to message to send when the task finish with success

While `Cmd.OfFunc.result`  just takes a message and dispatch it back.

I think `Cmd.OfFunc.result` should have a function to execute as a first argument and that `Cmd.ofMsg` should be re-introduced.

**Comment by et1975** [comment]
The intention was to give exactly the same capability to every computation
type, although I clearly messed up - `result` should have had just one arg
in each module.

The reason all other functions were made obsolete is the same FAKE4 ->
FAKE5 made all the functions obsolete, no matter how widely used... I'm
sure you can relate ;)

In any case, I can delay obsoleting the `Cmd.ofMsg` for now, but the
guidance remains the same - it may be gone, use the new module.

Published the new beta with these changes: 3.0.0-beta-8

**Comment by forki** [comment]
That fake 5 thing was @matthid not me ;-)

My problem here is not that things are made obsolete. That's fine. I'm more concerned with readability and now all those places in my elmish code look much more complicated. I always like how easy it felt and how easily I could teach it.

**Comment by et1975** [comment]
It wasn't a real dig at you guys, I like the reorg in FAKE5 even if all my
builds are complaining. I think with the matching module structure you now
should have easier time teaching - it's just like all F# collection modules
implementing the same functions on different types.

**Comment by forki** [comment]
I can clearly see the symmetry, but especially for the .return cases I think we regressed in readability.

**Comment by et1975** [comment]
Readability is in the eye of the beholder, but seriously, take this as an
opportunity to look at complicated cases and move them out into your own
`Cmd`-producing modules (a la `Navigation`).

**Comment by forki** [comment]
what do you mean? do you have an example?

**Comment by et1975** [comment]
Here's an example the lib authors can follow: https://github.com/elmish/browser/blob/master/src/navigation.fs#L30
But for app-specific needs, you probably don't need to know the structure of the `Cmd`, just use the core functions as primitives to implement your Cmd producers, that's all. Or, if you want to make it more testable, take a look at [OIDC](/elmish/OIDC).

**Comment by matthid** [comment]
I agree with @forki. I don't think I can "justify" this to my users ;)
Additionally, there is a visibility issue here. Finding the API within the `OfFunc` module is not straightforward.

Maybe we need to consider an exception here and remove the obsolete warning?

**Comment by matthid** [comment]
To add one thing: I like the other changes. Never quite understood the signature of `Cmd.ofAsync` for example.

**Comment by SCullman** [comment]
I was going to update my fable projects next week; and I was looking forward to the exciting innovations.
This issue is irritating. I am using Cmd.ofMsg everywhere and it doesn't look complicated to me, in contrast to the linked examples. 
Can someone please provide a __simple__ example as guidance?

**Comment by Zaid-Ajaj** [comment]
@SCullman 
```fs
open Elmish

module Cmd = 
  let ofMsg (msg: 'Msg) : Cmd<'Msg> = 
    [ fun dispatch -> dispatch msg ]
```

**Comment by et1975** [comment]
@SCullman What is the issue? Pre- 3.0.0-beta-8 obsolete warning would have told you exactly what to do and if you wanted to keep `Cmd.ofMsg` you could have just defined it in your code as:
```fsharp
module Cmd =
  let inline ofMsg msg = Cmd.OfFunc.result msg
```
But  3.0.0-beta-8 removed the warning and you get to keep the existing code warning-free.

**Comment by MangelMaxime** [comment]
@et1975 I think he was a bit lost when looking at the OIDC repo and how to create is own `Cmd`, `Program`, etc.

@SCullman According to @et1975 you should be able to use `Fable.Elmish 3.0.0-beta-8` and get no more warning when using `Cmd.ofMsg`. *If I understood correctly*

**Comment by forki** [comment]
(ftr this is healthy discussion. really appreciate it. Elmish is awesome!)

**Comment by kerams** [comment]
It would be really cool if the API here and in Fabulous could stay in sync in the future. I loved how I knew what was going on the first time I look at a Fabulous sample.

**Comment by et1975** [comment]
@kerams, i agree but your comment is misplaced. You could of course take
the Xamarin-specific stuff from there and build Elmish.Xamarin ;)
