### ISSUE TITLE
Cannot call program.onError in v3

### ISSUE THREAD

**Issue by dbrattli** [elmish/elmish#172]
### Description

In v3.0.0 it's not possible to call `program.onError`. Log module is internal and Program is private. Not a big deal to reimplement the logging but it was convenient to reuse for Elmish program mapping library authors because of the cross-platform capability. There's a `mapErrorHandler` but I don't see how it may help me. Should we not call `onError` anmore?

* elmish version: 3.0.0
* fable-compiler version: -
* fable-core version: 4.5.4
* Operating system: OS X

**Comment by et1975** [comment]
Hm, yes it was never not meant for user error reporting and the purpose of
`mapErrorHandler` is to change the default behavior so it's not going to do
anything for you either.
The takeaway here would be - elmish is not a logging libary, but if you
have you own logging then you can plug elmish into it, that is all.

**Comment by dbrattli** [comment]
Thanks for the quick answer.
