### ISSUE TITLE
Return signatures of new Cmd.Of functions should use Cmd

### ISSUE THREAD

**Issue by cmeeren** [elmish/elmish#173]
Return signatures should use `Cmd<'msg>`, but now use `(('msg -> unit) -> unit) list`.

![image](https://user-images.githubusercontent.com/7766733/57151947-6f565780-6dd2-11e9-9ff8-fa5bb9967888.png)

**Comment by Nhowka** [comment]
They are the same thing. Probably that happens because the function return type is not explicit now.

https://github.com/elmish/elmish/blob/69569e39876213e91c283c1c76bbe0fb88fba208/src/cmd.fs#L123-L131

**Comment by cmeeren** [comment]
Yes, that was what I was trying to say, thanks for clarifying it. :)

**Comment by et1975** [comment]
Released updated signatures as 3.0.2.
