### ISSUE TITLE
program.withTrace sends old model, not new one

### ISSUE THREAD

**Issue by cmeeren** [elmish/elmish#176]
I assume `withTrace` is supposed to allow customization of the same output you get with `withConsoleTrace`, but the function you supply receives the old state, not the new state, so it seems impossible to replicate `withConsoleTrace` behavior using `withTrace`.

**Comment by et1975** [comment]
Released 3.0.2 that calls the `trace` with the updated state. We can revisit `withTrace` signature for next major release, but for now further customization can be done with `Program.map`.

**Comment by cmeeren** [comment]
Tried 3.0.2 but the behaviour is still the same. Are you sure it's fixed?

**Comment by et1975** [comment]
Sorry, forgot to push the code. This should be in 3.0.2:  https://github.com/elmish/elmish/blob/master/src/program.fs#L80

Pretty sure this should be doing what it says on the tin...

**Comment by cmeeren** [comment]
Sorry, I'm confused: You forgot to "push the code" (unsure what that means in this particular context) but you say it should still be in 3.0.2?

**Comment by et1975** [comment]
Yes, I published the 3.0.2 from my machine, but pushed the commit to github just now.

**Comment by cmeeren** [comment]
Cleaned my bin/obj folders, things seems to have changed now. But there's a bug; the `trace` function must now return `'model * Cmd<'msg>` instead of `unit`.

**Comment by et1975** [comment]
Thanks, just published 3.0.3 with the correct signature.

**Comment by cmeeren** [comment]
There we go. Thanks! 👍
