### ISSUE TITLE
How to cancel a subscription from window.setTimeout

### ISSUE THREAD

**Issue by theimowski** [elmish/elmish#178]
### Description

I'd like to have an option of returning timeout id from `window.setTimeout` so that I can later use it to `clearTimeout`

### Repro code

```fsharp
let tickIn (timespan: TimeSpan) msg =
  let milliseconds = int timespan.TotalMilliseconds
  let sub dispatch =
    window.setTimeout((fun _ -> dispatch msg), milliseconds)
    |> ignore
  Cmd.ofSub sub
```

Because `sub` returns `unit` we need to ignore result of `window.setTimeout`
Is there any mechanism to pass this id somehow e.g. in return type of `tickIn`?

**Comment by et1975** [comment]
You can send a message with it.

**Comment by Zaid-Ajaj** [comment]
@theimowski Cancelable subscriptions must be applied on program (init, update, view) level. Here is the full program that implements a counter that ticks every second with a pause/resume button. 

[See it working in REPL](https://fable.io/repl/#?code=LYewJgrgNgpgBAUSsAlgZwBYDoDCBDKAY2jwBcQAnAKCoAoAqequfIk8iuNPYAB1gA0cAEYBPOAC08KMHACCAKzwKszAJogIcQngB2cAGYpds0BXjGDIOHmGbSiVJhsVCGFKRiFSEczZNcPPwwaDYOGKSkvGgAXAD0cTDI6NgA5h4YEMJYKCBxVPQAlDQgvDD6AGK2sLiUMFSl5XBVwjU4dVgAUmgAkrqeFKUNZZXVMFgASjB43sNNLTVTM6RYAAqD0XP6SE4YW4jJmJPTs1SkomVwAMqkZPAAvHAA3sxwb+0Q-XAxcMYOr28ACooQgAax6sh+AHleKRcroADx-AB8VAAvjRzpcALJoVJwR4AuAAHzggJAqVSsGBYLgRNJVxgpBp4NkIAMcBhcJAiJR9LgfUI5mA5X+bzeVFgDmMHlohQJzxYmi+jwAjABuMkg1kKgByPPgaKEOGAYCw7Nx+PJlOp2poAG0EQhUKRaAAiNBMvoDABuBFoABIAAxCAOqwpuwrIgC6kqZXC9-RgFD9UDgtAMP0+HjgAFpkXBs6R5bRdD8-vLyyq4Ao0LqyCgffUqI7nbK3YRYHgKN7k6nA0GI1HY1LtF2e0mUwR02Xfv1K4XdDnHrX63CmzRRxBeGA7nBgHiuLdPArXsAyG594eAO4ZOlvUmC4WivMFp5Hve30gYJWfByPNBj3GD4vgAajgVU4CNFhTSwXQDXvElriZFkIV+WR80VQDPzvVDZEeGQoONWD4N0eBXlJa0qRgFlXyJc9SEvbDPCwPC4C-H9+X1MjX0Q8VxVHbCKGZbVjHxQl+Mk8UDE+OAwHQXgLx-TCiSkqTRzhME0IAxNfWnDNZLlXj5LQRTGJ-J8YBFecIKDOzVLU-iTLMy9aEZEStNkNyQBFOBNNZQpigct5mJgIR7Q-YSWTEuBY34-krh8iwMILYK4EE8heGi3RxL4xzDFk5ylLo-K1M7aYJz0tNCLSxyivM9N3LY7iYCCxzQvCo9Smy-FYzjBxzBMZMPxPerLwkgT438wEYAAD3-PL+IYpigNY7U0I4tKGSSuAAH1eLdVY5AAVSuBA3S2uAWoOiYECuY7sXOukiXkn04Ai6N3rSjBII+964HZb0RuA5UHDitThAgSIeX+qFdBwKBtXTGT9H2zCxp-KjbTBeVPoiwDOGmuawaJcGqHWCkKB4LBgFBCnUip4A5xzbddxPQawGTKhiQLenGawDilm8K5RF0NxBngiBQjdJJdlzPBeF4C6ebgPnqYoT4qCAA&html=DwCwLgtgNgfAUKApgQwCbwAQeBRZkbhgAOAtIgI4CuAlgG4C8A5AMID2AdmIl6QCoBPYoiYYAxp25dm3AB5gA9OGgBucSGQAnAM54GVMADNSADiaZs2sZprEwGbZrEMARAH03ACQDyAZT4eClA0AEbaCpooYmAAdMSabKhU0TScMRA0HDEAVtouMMAKVjZ2FsDFtvaOzu5efgFuQaHhkcjRpKhsEHEJSSlpGVm5+YUVpQhKKOgIIYkC4lDI2tquyMRkElzImYia+XBYWMCo9Bg0qK6IUBnaIKRrxC4LSysuVzd3DyMKJ3TwhbNUAJ-kpILAgA&css=Q)

```fs
type State = {
    Count : int 
    TickId : Option<int>
}

type Msg = 
    | ToggleTick 
    | SetTickId of Option<int>
    | Increment 
    
let init() = { Count = 1; TickId = None }, Cmd.ofMsg ToggleTick

[<Emit("setInterval($0, $1)")>]
let setInterval (f: unit -> unit) (n: int) : int = jsNative

[<Emit("clearInterval($0)")>]
let clearInterval (n: int) : unit = jsNative

let update msg state = 
  match msg with 
  | Increment -> { state with Count = state.Count + 1 }, Cmd.none 
  | SetTickId id -> { state with TickId = id }, Cmd.none 
  | ToggleTick ->
    match state.TickId with 
    | None -> 
        let startTicking = 
            fun dispatch -> 
                let tickId = setInterval (fun () -> dispatch Increment) 1000
                dispatch (SetTickId (Some tickId))

        state, [ startTicking ]
    
    | Some id -> 
        let stopTicking = 
            fun dispatch ->
                clearInterval id 
                dispatch (SetTickId None)

        state, [ stopTicking ]

let render state dispatch = 
    let tickText = 
        match state.TickId with
        | Some _ -> "PAUSE"
        | None -> "RESUME" 

    div [ ] [
        h1 [ ] [ ofInt state.Count ]
        button [ OnClick (fun _ -> dispatch ToggleTick) ] [ str tickText ]
    ]
  
Program.mkProgram init update render
|> Program.withReactSynchronous "elmish-app"
|> Program.run
```

**Comment by theimowski** [comment]
Right, that makes sense! 
I was constrained in thinking that it should come in a single message, but it doesn't really.
Thanks!
