### ISSUE TITLE
Potential reset of syncDispatch

### ISSUE THREAD

**Issue by fdbeirao** [elmish/elmish#180]
### Description

In line [125 of program.fs](https://github.com/elmish/elmish/blob/master/src/program.fs#L125) we see that the `map` function resets the program's `syncDispatch` back to `id`. I am not familiar enough with Elmish to understand if this is indeed the desired behaviour or an actual bug. I would expect the `map` function to leave syncDispatch as what was provided to it.

Something like the pseudo-code:

```fsharp
let map mapInit mapUpdate mapView mapSetState mapSubscribe
            (program: Program<'arg, 'model, 'msg, 'view>) =
        { program with 
          init = mapInit program.init
          update = mapUpdate program.update
          view = mapView program.view
          setState = mapSetState program.setState
          subscribe = mapSubscribe program.subscribe }
```

**Comment by Nhowka** [comment]
Using the `with` would lock the program to be of the same type, making the `map` lose its function. As both are made to library developers and `syncDispatch` is too niche, having it as an additional argument is not that important. You just need to make sure to call `withSyncDispatch` always after `map`.

**Comment by et1975** [comment]
What @Nhowka said.
