### ISSUE TITLE
Provide an Elmish package that is 2.x compliant

### ISSUE THREAD

**Issue by fdbeirao** [elmish/elmish#181]
### Description

After the investigation that lead to #179 , I was surprised to find that it is ["normal/by design"](https://github.com/elmish/elmish/pull/179#issuecomment-501809876) that Elmish 3.x is no longer thread safe ([Elmish 2.x used a MailboxProcessor](https://github.com/elmish/elmish/blob/v2.x/src/program.fs#L90) for the event loop). 

I haven't used Elmish for long enough to understand the underlying motivation for moving away from the MailboxProcessor. I found something related to [UI thread synchronization](https://github.com/elmish/elmish/commit/07c021c0403188e7c16678e08ba0d9c79f6dbe50), but I'm not 100% sure that's the underlying motivation.

What I do know is that the non thread safe nature of the `Elmish` package completely undermines the original appeal of the Elm architecture. The way **I see it**, I design my systems using the MVU architecture, exactly so I don't have to think about multi-threading concurrency problems, and I can just think in terms of state+msg. Then, the way I address "concurrency" is exactly by the fact that state can be different when I observe message 1 vs 2. But this only works if state is monotonically increasing after each update (not observed twice).

My point is: I don't see the appeal (as an end user) of Elmish 3.x *as is*. I understand you can use it for Elmish.WPF or even other UI frameworks perhaps, but for the very simplified case of a console application, it doesn't work. It's not Elm architecture anymore.

### Expected and actual results

I expect there to be a package `Elmish.""xyz""` that when I reference it from nuget and add it to my project allows me to use the MVU architecture in a thread safe way. Whether this package uses `refs`, `locks`, `mailboxes`, `mutexes`, `semaphores`, `fairydust` or whatever under the covers is transparent to the user of this package.

All that I want is to be able to observe a monotonically increasing model, at the cost of deterministic ordering of messages for `Cmd.batch` operations. Right now I don't see how I can accomplish this in Elmish 3.x.

I admit there must be a solution, but I am quite simply not proficient in F# enough to provide my own `syncDispatch`. Also the `withSyncDispatch` function does mention that it is only [meant to be used by library authors](https://github.com/elmish/elmish/blob/master/src/program.fs#L110-L111), which is definitely not my use case.

I hope this message doesn't come as too aggressive. Don't get me wrong, I absolutely love Elm and the work you guys provide with Elmish. I just want the best for the community. Let me know how I can be of assistance. Cheers. 🙏🏻

**Comment by et1975** [comment]
2.x is not a spec, so there's nothing to be compliant with. We had good reasons to change the behavior, leaving the door open for any sync mechanism. I'll leave this open for now in case someone wants to provide a `syncDispatch` implementation that meets your criteria.

**Comment by boeremak** [comment]
I just read this and I do agree with @fdbeirao . I like the simplicity of reasoning about thread safe code in the "older" version.

**Comment by et1975** [comment]
Any reason you can't keep using version 2.x?

**Comment by boeremak** [comment]
Not really, it's just that I'd like to keep up with newer versions because the other one is bound to be deprecated somewhere along the line.

**Comment by bender2k14** [comment]
@et1975 said...
> We had good reasons to change the behavior, leaving the door open for any sync mechanism.

...which means that the previous synchronization mechanism via `MailboxProcessor` should still work.  I pushed a branch with the single commit https://github.com/bender2k14/elmish/commit/277f7949ed528af1b0deaab61ee1d57b70546996 that attempts to do just that.

@fdbeirao and @boeremak, can you test this and see if it works?  In any project where you are currently using Elmish 2.x, you can upgrade to the latest release, copy-paste that code into your project, and then call `|> withMailboxProcessor` just before you call `|> run` or `|> runWith`.

> ...the `withSyncDispatch` function does mention that it is only meant to be used by library authors, which is definitely not my use case.

The code I wrote uses `withSyncDispatch`.  I see using it for unintended purposes as less of an issue than that fact that @et1975 expects to remove this function in the next major release https://github.com/elmish/elmish/issues/185#issuecomment-519520317.  However, that isn't much different than what you are going through now trying to figure out the migration path from 2.x to 3.0.  You two and us over at https://github.com/elmish/Elmish.WPF/issues/112 can cross the 3.x to 4.0 migration-path bridge together in the future.

**Comment by et1975** [comment]
I believe the solutions has been provided, closing.

**Comment by bender2k14** [comment]
@et1975, what do you think about merging https://github.com/bender2k14/elmish/commit/01d21d5555201ee36953309ae4e4a548601eea7e into `master`?

**Comment by et1975** [comment]
@bender2k14 If you look closely I've removed `withSyncDispatch` from `master` already and I don't want elmish core to carry any sync mechanism (for the same reason elmish.browser and elmish.react are separate packages - specific implementations for specific needs).
