### ISSUE TITLE
Having trouble with upgrading

### ISSUE THREAD

**Issue by forki** [elmish/elmish#184]
![image](https://user-images.githubusercontent.com/57396/60278773-51076680-9900-11e9-8cc0-c5887c20b3de.png)

It seems the view function is private?
Any ideas what I can do?

**Comment by MangelMaxime** [comment]
@forki Yes, in Elmish 3, with made the `Program` opaque. 

You can now use [`Program.map`](https://github.com/elmish/elmish/blob/master/src/program.fs#L117) in order to modify it.

If you need to access the `view` you can use [`Program.view`](https://github.com/elmish/elmish/blob/master/src/program.fs#L107)

**Comment by forki** [comment]
Thank you. Will try.

Maxime Mangel <notifications@github.com> schrieb am Do., 27. Juni 2019,
19:31:

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/60290471-24137d80-9919-11e9-9407-44fe6f760323.png)

I'm one step further. But no touchdown

**Comment by MangelMaxime** [comment]
Hum is it normal to have a `dispatch2` in your `setState`?

**Comment by forki** [comment]
No it's not. I was very confused that the map function required such a signature

**Comment by MangelMaxime** [comment]
Ah no, it's not a second dispatch, the first argument is the coming from the `program` we are mapping against.

[Source from Elmish.HMR](https://github.com/elmish/hmr/blob/master/src/hmr.fs#L101-L105)
```fs
        let mapSetState setState (model : Model<'model>) dispatch =
            match model with
            | Inactive -> ()
            | Active userModel ->
                setState userModel (UserMsg >> dispatch)
```

**Comment by forki** [comment]
that link to HMR helped a lot! thanks
