### ISSUE TITLE
How to use withSyncDispatch

### ISSUE THREAD

**Issue by albertwoo** [elmish/elmish#185]
### Description

I am using Fable with Elmish to do server side rendering. The problem is if some update functions return a command which is Async then Program.run will not wait the async command finishing. Currently I made my own Cmd.ofAsync to use RunSynchronously. But this way I cannot get the benifit of thread pool.
Is there any other way to do it, and what is withSyncDispatch meant to be used to.

**Comment by et1975** [comment]
`syncDispatch` is an implementation detail of the dispatch loop to synchronize access to internal state, it will be removed from the `Program` API in the next release and there's no good reason for an end-user to touch it.
Personally I'm not using SSR, maybe someone else can comment on your situation, but I don't believe it was meant to be used the way you do it.

**Comment by forki** [comment]
OK jumping in here. We use SSR as well, but actually just the view part of elmish is relevant on the server. There is no update loop running.
To get the initial model we have a separate init function for SSR. This one is sync and does not spawn new commands.

In "classic" elmish that runs in the browser you often have commands from the init that just async load additional data via http requests. In SSR you do that in one go. Just fill it directly into the initial model. This is what makes it so crazy fast. In our case we save gazillions of requests and just do Redis calls in the SSR init function.

**Comment by albertwoo** [comment]
@forki Thanks for your comment.
At first I use that strategy too, but it requires me to write a lot of code to achieve that. So I was thinking to make a server side Program.run to handle those update loop. It saved me a lot of time and everything is great except for the async stuff. But it is ok for now, because I can just use  RunSynchronously and after the view is rendered I will cache those generated html.

**Comment by forki** [comment]
@albertwoo yeah it's more work. But it's OK since the process of doing it is usually compeletely different on server and client
