### ISSUE TITLE
Exception prevents remaining update command subscriptions from executing

### ISSUE THREAD

**Issue by bender2k14** [elmish/elmish#186]
Each subscription in a command is executed [via](https://github.com/elmish/elmish/blob/master/src/cmd.fs#L25-L26)
```
let internal exec (dispatch:Dispatch<'msg>) (cmd:Cmd<'msg>) =
    cmd |> List.iter (fun sub -> sub dispatch)
```

so if some subscription throws an exception, then none of the subscriptions after it are executed.

This behavior can also be verified with this example and a breakpoint inside of the function `g`.  When using the first definition for `f` (that does _not_ throw an exception), the function `g` _is_ executed.  When using the second definition for `f` (that _does_ throw an exception), the function `g` is _not_ executed.
```fs
module Program
open Elmish
let mutable dispatch : Dispatch<unit> option = None
module App =
  let init () = (),[]
  let update msg model : unit * Cmd<unit> =
    let f = fun d -> ()
    //let f = fun d -> failwith "update command exception"
    let g (d:Dispatch<unit>) = ()
    (),[f; g]
  let view _ d =
    dispatch <- Some d
    ()
[<EntryPoint>]
let main _ =
  Program.mkProgram App.init App.update App.view
  |> Program.runWith ()
  |> ignore
  match dispatch with Some d -> d () | None -> ()
  0
```

Is this the intended behavior?

My expectation was that all subscriptions in a command would always be executed.

**Comment by et1975** [comment]
There is no one right way to handle exceptions from a collection of cmds, so we don't even try.
The existing handler is the last line of defence for the developer to give you some context, not a norm you should have in your application, that's why the core `Cmd` API guides you towards always handling it and either produce `onSuccess` or `onFailure` or use the version that will swallow one of the outcomes.
If exception is an expected norm in your case, you should handle it and emit a message.

**Comment by bender2k14** [comment]
I agree that having a last line of defense is a good thing and that expected exceptions should be handled by emitting a message.  The exceptions that I have in mind are the unintended ones, and I am considering what Elmish could do to make applications built on it as robust as possible.

Is the design of `Cmd<'msg>` intended to allow users of Elmish to define their own command implementations (instead of always using the core `Cmd` API)?

This seems especially the case when considering that `Cmd.ofSub` (with type `Sub<'msg> -> Cmd<'msg>`) exists, is not referenced in Elmish, and the core `Cmd` API doesn't provide any guidance as to how one should create instances of `Sub<'msg>`.

**Comment by et1975** [comment]
Yes, the expectation is that you'd create your own Cmd whenever one from the core lib doesn't meet the needs. [The docs](https://elmish.github.io/elmish/subscriptions.html) kinda give you an example of `Cmd.ofSub` and @MangelMaxime has a [long post](https://medium.com/@MangelMaxime/my-tips-for-working-with-elmish-ab8d193d52fd) on defining custom Cmds.

**Comment by bender2k14** [comment]
Thank you for those links.  There were very helpful.

One thing from @MangelMaxime's post that I didn't expect was that all of his `ofSuccess` and `ofError` functions were just `'msg` case constructors.  I guess that makes sense in hindsight as those are the simplest possible functions of those types.

Is that the recommended approach?

**Comment by MangelMaxime** [comment]
Hello @bender2k14 for me it makes sense because `ofSuccess` and `ofError` jobs are to send the result of either branch into the `update` function via the `Msg`. And then in the `update` function, you handle the different cases.

Did I get the expected result? 

- Yes, so let's do something about it
- No, then show a message to the user and send a log to the server for example
- etc.

**Comment by bender2k14** [comment]
This sounds like a good approach.  I can get used to that.  Thanks @MangelMaxime.

**Comment by bender2k14** [comment]
Even though I expected all the subscriptions in a command to always be executed (even if one of the subscriptions throws an exception), I don't mind the current behavior.  With this issue, I wanted to at least confirm that this is the intended behavior.  You have done that for me @et1975 (and more!).  Thanks :)

**Comment by bender2k14** [comment]
I have never used Elm (or its Model, View, Update architecture) before, so I am sure some things about Elmish are clear to those that have programmed in Elm that are not clear to me.

My understanding of Elm is that it is a purely functional language.  In particular, the `update` function must be pure.  To execute impure code, one creates a command that represents impure behavior and gives it to the Elm dispatch loop to execute.

If it is not too much trouble, could someone let me know if my understanding is correct or point out where I am mistaken?
