### ISSUE TITLE
On passing 'msg last into update

### ISSUE THREAD

**Issue by bender2k14** [elmish/elmish#187]
In #130 while discussing a different issue, @et1975 [said](https://github.com/elmish/elmish/issues/130#issuecomment-360817750)
> As long as we are making breaking changes, how does everybody feel about reversing the order of msg and model in update? 😱
> 
> This could make update look like this:
> 
```
let update model = function
     | Msg1 m -> ...//
     | Msg2 m -> ...//
```
> hides 👀

As far as I can tell, the responses to this comment were all in favor of this change.

Maybe nothing happened because @et1975 went into hiding 😛 (or maybe there is an in-joke that I don't know about).

In all seriousness though, I have been working in Elmish now for about a week, and this thought has already occured to me as well.

My guess is that the current argument order is because this is the order in Elm.  Since Elmish is written in F#, it makes sense for its implementation of the MVU architecture to be idiomatic for F#.  Either order has its advantages and disadvantages.

Is there anyone who prefers the _current_ order or does _not_ want to make this breaking change in the next major release?

I ask it in that way since nobody voiced any opposition when this change was originally suggested.  Of course those that previously expressed some amount of support for this change (including @et1975 himself) are more than welcome to have a different opinion now.  (I hate how society at large tends to ridicule people that change their minds even though new information is available or simply time has passed.)

Certainly it is easy for users to definite all their `update` functions with the opposite order and then flip the order just for the function passed to Elmish.

**Comment by MangelMaxime** [comment]
Personally, I am fine with the current order because in bigger application your `update` function has more than 2 arguments. 

Remember that everything is a function in the end, so  `view`, `init`, `update`, etc. can take any number of arguments in any order.

For example:

```fs
let update (context : Context) msg model =

let init (context : Context) (zoneConfigId : int option) =

let view (zone : MarkerJson) (color : string) (model : Model) (dispatch : Dispatch<Msg>) =
```

I don't think making a breaking changes makes sense in regards to this situation. Switching the argument order will also make all the resources blog, samples, videos broken and so for newcomers, they will probably find the outdated tutorials and so have a bad first impression which is something to avoid.

**Comment by bender2k14** [comment]
> Personally, I am fine with the current order because in bigger application your update function has more than 2 arguments.

I should have stated things more clearly.  Instead of swapping the `'msg` and `'model` types, I really meant to have the `'msg` type last.  Now hopefully it is clear that the number of arguments to `update` is irrelevant.

I will update the issue title to match.

**Comment by bender2k14** [comment]
> Remember that everything is a function in the end, so view, init, update, etc. can take any number of arguments in any order.

Certainly.  I am not trying to discuss what can be done.  I am trying to discuss what should be done.

**Comment by halcwb** [comment]
This is really a no-brainer:

```
let updateReverse model = function
    | NavBarMsg _ -> model, []
    | _ -> model, []

#if DEBUG
open Elmish.Debug
open Elmish.HMR
#endif

Program.mkProgram init (fun msg model -> updateReverse model msg) view

```

No need to change elmish.

P.S. This is also the joy of functional programming. If you are not happy with the DSL, it is very easy to create your own.

**Comment by bender2k14** [comment]
@halcwb, I am not asking how I could or if I can.  I am suggesting that this order is better for everyone.

**Comment by et1975** [comment]
I implemented this idea in a branch with other changes that would have had
major impact on the end user. In the end the branch was scrapped as a bad
idea along with the change in the order of parameters.
I don't see it happening at this point.
I'm also not under illusion that it would have been better for everyone -
for starters the composition via 'function'  would go against F# guidelines.
On a general note, I'd suggest writing one or two applications with elmish
the way it is to get a feel for what the real pain points are. I'm quite
sure everyone who does develops utilities that make it easy for them to
work with it the way they like, in this case it's the flip function, but
we've also seen people introducing component interfaces.
Better for everyone is a really tall order, especially when existing code
bases are a factor.

**Comment by bender2k14** [comment]
> ...the composition via 'function'  would go against F# guidelines.

Are you referring to the section of the F# coding conventions called [Partial application and point-free programming](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/conventions#partial-application-and-point-free-programming)?

> I'm also not under illusion that it would have been better for everyone...
> ...
> Better for everyone is a really tall order, especially when existing code bases are a factor.

When said...
> I am suggesting that this order is better for everyone.

...I was mostly trying to make a very stark contrast between the ideas "I want something for me" vs "I want to help others".

So many of my comments in Elmish issues have been interpreted as me asking for how I can use Elmish to do what I want.  I appreciate the concern and the desire to help me and others like me.  This goodwill makes for a great community, and I am happy to have recently begun contributing to it.  To those people, I said, "Rest easy; I am doing fine".  I have never been more excited to write a program than I am now as I [lead a team that will makes a Windows desktop application using Elmish.WPF](https://github.com/elmish/Elmish.WPF/issues/105#issuecomment-524628014).

Of course I also wasn't suggesting that the process of changing would be better for everyone.  Quite the opposite; I would expect that the process of chaning would be worse for everyone.

More precisely, I my suggestion is that (_after_ the process of making the change) passing `'msg` last into `update` would be a [Pareto efficient](https://en.wikipedia.org/wiki/Pareto_efficiency) move, which means that no one is worse off and at least one person is strictly better.

Communication is hard.  Determine how many details to include in order to be correctly understand by everyone (let alone anyone) seems like an impossible problem.  I will keep trying to do my best.

> ...we've also seen people introducing component interfaces.

I don't know that you mean.  Is there some example or resource I could read to learn about this?
