### ISSUE TITLE
Throttling in Elmish

### ISSUE THREAD

**Issue by bender2k14** [elmish/elmish#189]
Is a clean way to do throttling in Elmish?

My definition of throttling comes from [this SO answer](https://stackoverflow.com/questions/25991367/difference-between-throttling-and-debouncing-a-function/25991510#25991510).

### Previous Work

Throttling has be discussed a bit in other issues.
1. @MangelMaxime demonstrated React-dependent throtting in https://github.com/elmish/elmish/issues/183#issuecomment-506034256.
2. @Zaid-Ajaj demonstrated a similar concept in https://github.com/elmish/elmish/issues/151#issuecomment-407224140, but not throttling as defined in the SO answer (maybe this could be called "limiting" as in [rate limiting](https://en.wikipedia.org/wiki/Rate_limiting)).
3. @Zaid-Ajaj also demonstrated another concept described as throttling in https://github.com/elmish/elmish/issues/122#issuecomment-340435460.

I see three issues with that last example by @Zaid-Ajaj compared to what I want.  Here they are from least to most severe.

1. `update` is impure because it calls `DateTime.Now`.
2. It doesn't implement throttling as defined in that SO answer.  For example, suppose the throttle time is 10 seconds and two messages arrive one second apart.  This implementation would only process the initial message right away.  The desired behavior (according to the definition in the SO answer) would process the first message right away and the second message 10 seconds later.
3. The implementation heavily involves the `init`, `Model`, `Msg`, `update`, and `Cmd` details of a user's Elmish program.  For example, if the original message to throttle was called `MakeRequest`, then this solution splits that message into two: `StartLoadingData` and `ActuallyMakeRequest`.  I see throttling as a [cross-cutting concern](https://en.wikipedia.org/wiki/Cross-cutting_concern), so instead of solving throttling via the normal Elmish means (such as by increasing the number of message types), I would prefer an "[aspect-oriented programming](https://en.wikipedia.org/wiki/Aspect-oriented_programming) solution" that doesn't depend on the user changing their existing message types.  That is what I mean by "clean".
4. `update` is still called for every throttled message...even for the messages that are supposed to be no-ops due to throttling.

@MangelMaxime demonstrated a similar solution for debouncing [here](https://mangelmaxime.github.io/Thoth/elmish/debouncer.html).  In addition (of course) to being for debouncing instead of throttling, this implementations also has disadvantages 3 and 4 from above.

### My Problem

The specific issue I am facing is a [WPF Slider](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.slider?view=netframework-4.8) with a discrete interval with a length of 8000.  As the user drags the thumb (as it is called) of the slider, each integral value encountered dispatches a message.  My `update` function is trivial: it just saves the new value of the slider in the model.  It is not computationally expensive like in the second example by @Zaid-Ajaj.  The part that is computationally expensive is `update` being called ~4000 in a single flick of the user's wrist.  I would expect my application to be less performant if I were to implement a throttling solution that was similar to the second example of either @MangelMaxime or @Zaid-Ajaj in which I enlarge my `Model` and `Msg` types thereby causing `update` to do even more work.

### Potential Solutions

From my position in "user land", one solution I see is to move all the no-op logic into my application's top-level `update` function.  Then, even though `update` is called for every no-op (because of throttling) message, I can minimize the execution time.  However, this is exactly the opposite of what I would call an "aspect-oriented programming solution".  Now the implementation of the root of my `update` "tree" changes because of implementation details most closely related to leaves of the `update` "tree".

The solution that I am currently looking into is throttling the events raised by the WPF Slider (thereby preventing them from ever being converted into messages and sent to the dispatch loop).  It is easy to cancel events in WPF.  The hard part (as with the second example from @Zaid-Ajaj and issue 2 above) is merely delaying (instead of canceling) the "last" message in some interval.  I expect that I will find a way to make this work though.  The disadvantage is that it is WPF specific let alone Slider specific.

I would prefer a cleaner solution in Elmish.  The dispatch loop holds on to a custom FIFO queue (of type `RingBuffer`) that stores all the messages that have been dispatched but not yet passed to `update`.  We don't have to modify the `RingBuffer` code in order for Elmish to directly support throttling, debouncing, and limiting.  To support these three operations, we just have to
1. insert a layer of indirection between the beginning of the dispatch loop and the `RingBuffer` instance and
2. expose a mechanism for users to cause messages of a certain type to be dropped or delayed.

This idea seems similar to my very limited understanding of Elmish.Streams, which was recently [renamed](https://github.com/dbrattli/Fable.Reaction/commit/085f9f35002355d8021e2cf577540175d613fc16) (back) to Fable.Reaction.

**Comment by Zaid-Ajaj** [comment]
If you don't want the `update` function to be called, then throttling or debouncing should happen at the dispatch level from your user interface by making a throttled version of dispatch before even dispatching the event.  I am not sure how this would work in Elmish with WPF but this is how it works with React and Elmish

```fs
let debounce =
  let timeoutIds = ResizeArray<float>()
  fun (timeout: int) (callback: unit -> unit) ->
    let delayed = fun _ ->
      for timeoutId in timeoutIds do Browser.Dom.window.clearInterval(timeoutId)
      callback()
    timeoutIds.Add(Browser.Dom.window.setTimeout(delayed, timeout))

let render state dispatch = 
    Slider.slider [
        Slider.valueOrDefault state.Value
        Slider.onChange (fun value -> debounce 1000 (fun _ -> dispatch (SetValue value)))
    ]
```
if the behavior you want is: 

> process the first message right away and the second message 10 seconds later

then change `debounce` such that it triggers the first message right away and `debounces` other incoming messages:
```fs
let debounce =
  let timeoutIds = ResizeArray<float>()
  fun (timeout: int) (callback: unit -> unit) ->
    if timeoutIds.Count = 0 then dispatch msg // see this line
    let delayed = fun _ ->
      for timeoutId in timeoutIds do Browser.Dom.window.clearInterval(timeoutId)
      callback()
    timeoutIds.Add(Browser.Dom.window.setTimeout(delayed, timeout))
```

Now if you don't care about your update function being called a lot and you only care about delaying the processing of a certain message, then you can create a command that debounces the incoming message before processing it by the `update` function:
```fs
module Cmd =
  let debounce =
    let timeoutIds = ResizeArray<float>()
    fun (timeout: int) (msg: Msg) ->
      let debouncer (dispatch: Msg -> unit) : unit =
        let delayed = fun _ ->
          for timeoutId in timeoutIds do Browser.Dom.window.clearInterval(timeoutId)
          dispatch msg
        timeoutIds.Add(Browser.Dom.window.setTimeout(delayed, timeout))
      Cmd.ofSub debouncer
```
Now you can use it in your `update`:
```
let update msg state = 
  match msg with
  | SetValueDebounced value -> state, Cmd.debounce 1000 (SetValue value)
  | SetValue value -> { state with SliderValue = value }, Cmd.none

 let render state dispatch = 
    Slider.slider [
        Slider.valueOrDefault state.Value
        Slider.onChange (fun value -> dispatch (SetValueDebounced value)))
    ]
```
Of course, don't mind the imaginary component `Slider`, I hope you get the idea

**Comment by cmeeren** [comment]
I agree that wrapping `dispatch` is the way to go for throttling/debouncing/etc. if what you want to achieve is simply dispatching a frequent message less often (as in the case of the slider).

**Comment by bender2k14** [comment]
> If you don't want the update function to be called, then throttling or debouncing should happen at the dispatch level from your user interface by making a throttled version of dispatch before even dispatching the event.

Oh, yes.  Great observation @Zaid-Ajaj!  In fact, `withSyncDispatch` is almost enough.  If...
https://github.com/elmish/elmish/blob/26b9ae3cbb3484d9fd0dabb319f4ffcfa6740b84/src/program.fs#L115-L118

...were implemented as...
```
let withSyncDispatch (syncDispatch:Dispatch<'msg> -> Dispatch<'msg>)
                     (program: Program<'arg, 'model, 'msg, 'view>) =        
    { program
        with syncDispatch = program.syncDispatch >> syncDispatch }
```

...then throttling, debouncing, and limiting of messages could be added in one call to `withSyncDispatch` and the race conditions of `dispatch` could be removed in another (such as by calling `withMailboxProcessor` https://github.com/elmish/elmish/issues/181#issuecomment-530534973 or only executing `dispatch` on a [particular thread](https://github.com/elmish/Elmish.WPF/blob/5df8514ce4452883a1e417c9f6f479f545339f9e/src/Elmish.WPF/Program.fs#L28)).

However, I agree with @et1975 when he said in https://github.com/elmish/elmish/issues/185#issuecomment-519520317 that
> ...there's no good reason for an end-user to touch [`syncDispatch`].

Instead, it seems like a good idea to me to expose throttling, debouncing, and limiting behavior to the end-user through functions that look something like...
```
let throttle (predicate: 'msg -> bool) (time: TimeSpan) program = ...
let debounce (predicate: 'msg -> bool) (time: TimeSpan) program = ...
let limit (predicate: 'msg -> bool) (time: TimeSpan) program = ...
```

...and their implementation would make use of the function composing implementation of `withSyncDispatch`.

I could certainly be missing something though, so I am interested to hear what others think about this.

**Comment by cmeeren** [comment]
Oh, I think I see the confusion. In Elmish.React the `view` function calls `dispatch` as needed. In Elmish.WPF however, the `bindings` ("view") function never calls `dispatch`; the bindings are just creating an `ICommand` or setting up a two-way binding that internally calls `dispatch`.

I still think a good general solution is to wrap calls to `dispatch` for the specific bindings where it's needed. From the top of my head, that would require extending two-way and `Cmd` bindings with a new optional `modifyDispatch` parameter with signature `Dispatch<'msg> -> Dispatch<'msg>`). Here you could pass in any throttling, debouncing etc. The Elmish.WPF internals would then use this modified dispatcher.

As an example usage: If you have a function `debounce : int<ms> -> Dispatch<'msg> -> Dispatch<'msg>` then you'd do e.g. `Binding.cmd (SomeMessage, debounce 500<ms>)`

**Comment by MangelMaxime** [comment]
> (In React, `view` is evaluated for each update, and any calls to `debounce` inside `view` will create a new debounced version each time `view` is called, defeating the purpose.)

I am not sure I understand correctly on this point.

There is several things to consider for Elmish.React. 

Indeed, dispatch is not a stable reference so in theory React will re-render the view each time but your whole view is wrapped in a [`LazyView`](https://github.com/elmish/react/blob/master/src/react.fs#L31) and so react will make a deep pass on your views, only if your model actually changed between "2 frames".

Also, it will not necessarily create a new debounced version each time. If you use function component (set up correctly with `equalsButFunctions`), stateful component, ... then the view below that component will re-render only if something changed.

A new debounced version will be created only if there is a need for it. If you debounce an input, then it will trigger a debounce only when having the expected user interaction in it. 

That's what I have shown in this example: https://github.com/elmish/elmish/issues/183#issuecomment-506034256

**Comment by Zaid-Ajaj** [comment]
> Also, it will not necessarily create a new debounced version each time. If you use function component (set up correctly with equalsButFunctions), stateful component, ... then the view below that component will re-render only if something changed.

> A new debounced version will be created only if there is a need for it. If you debounce an input, then it will trigger a debounce only when having the expected user interaction in it.

@MangelMaxime even a function component isn't needed because it doesn't matter whether dispatch is stable, it is `debounce` that has to be stable which is the case in my example above

**Comment by bender2k14** [comment]
Here is my summary.  The journey of a message is from where it is created, into `dispatch`, through Elmish code, and lastly into `update`.  Throttling a particular message should be done near the beginning of this journey (between where it was created and being passed into `dispatch`), not near the end (such as in Elmish code as I was proposing or inside `update` as some examples showed).

We are in the process of adding this functionality to Elmish.WPF now (https://github.com/elmish/Elmish.WPF/issues/114).

Thanks everyone the comments :)
