### ISSUE TITLE
Access `init` and `update` in test-code

### ISSUE THREAD

**Issue by matthid** [elmish/elmish#192]
### Description

While upgrading, I noticed that the `init` and `update` functions are no longer publicly available.
The current workaround is to use:

```fsharp

open Fable.Core
open Fable.Core.JsInterop
open Elmish

[<Emit("$0 === undefined || $0 === null")>]
let isNullOrUndefined r : bool = jsNative

module Program =
    let init (p:Program<'arg,'model,'msg, _>) : 'arg -> 'model * Cmd<'msg> =
        let res : Func<'arg, 'model * Cmd<'msg>> = p?init
        if isNullOrUndefined res then
            failwithf "Could not get init function from program"
        res.Invoke
    let update (p:Program<'arg,'model,'msg, _>) : 'msg -> 'model -> 'model * Cmd<'msg> =
        let res : Func<'msg, 'model, 'model * Cmd<'msg>> = p?update
        if isNullOrUndefined res then
            failwithf "Could not get update function from program"
        fun msg model ->
            res.Invoke(msg, model)
```

Which was surprisingly tricky to implement. The reason we use those functions are integration tests to verify some domain specific behavior.

**Comment by bender2k14** [comment]
> While upgrading...

From what version to what version?

**Comment by et1975** [comment]
@matthid yes, in v3 the `Program` structure is an implementation detail, I didn't forsee the need to access the `init`, but we already have examples of other accessors ([`view`](https://github.com/elmish/elmish/blob/master/src/program.fs#L111)), so I'd have no concerns adding accessors for `init` and `update`.

**Comment by matthid** [comment]
> From what version to what version?

I don't want to tell. What I can tell is that we are slow moving and we made bad experiences when upgrading, including fable compiler bugs... And we have to support stuff a long time.

**Comment by bender2k14** [comment]
> ...we are slow moving...

Moving slow is not inherently a bad thing.  I hope you are not ashamed of it.

> > From what version to what version?
> 
> I don't want to tell.

Do you mind then answering the meta question of way you don't want to tell?  I am genuinely interested in your experience and development process with Elmish.

**Comment by matthid** [comment]
> I am genuinely interested in your experience and development process with Elmish

Sure, it is very nice, because:
- it gives us an easy way to express quite a "complicated" setup (not particularly for technical reasons), which probably would be very hard to do in angular for example. We basically load components dynamically.
- We have done various refactorings, and while they obviously involve work things tend to work
- we are fast in adding new stuff and cleanup later when we feel like we got the idea

It is painful, because:
- Obviously people get very limited/broken tooling. Everything feels like taped together
- We have huge problems in the team with npm and paket updates, especially since we want to stay on more stable versions.
- It is surprisingly hard to actually find older versions of stuff working together

The reason we decided to update is because of a json serialization bug due to mixing newtonsoft on the server and thoth on the client. Basically, we only wanted to update this one thing but due to a trail of bugs we followed, we now update everything...

@MangelMaxime already knows we are not exactly on the most basic use case and we tend to trigger lots of bugs everywhere. Therefore we depend on internals to workaround them. Therefore things tend to break on upgrades. Therefore we prefer to stay on older versions.

We try to keep reporting and PRing stuff but I can tell you that costs again lots of time we already don't have when we find issues. And sure enough often I fail to reproduce stuff on smaller samples and give up eventually (as debugging is another not so nice area ;))

Sorry for the long post. I hope this answers your question ;)

**Comment by et1975** [comment]
Also, we already have `mapInit`/`mapUpdate`, maybe that could do it for you as well? You can even override/wrap both in one go with `Program.map`, just pass `id` to the rest of the args.

**Comment by bender2k14** [comment]
That was very interesting @matthid.  Thanks for sharing :)

> ...we are not exactly on the most basic use case and we tend to trigger lots of bugs everywhere. Therefore we depend on internals to workaround them. Therefore things tend to break on upgrades.

Oh, no!  That is quite the death spiral :'(

**Comment by matthid** [comment]
@et1975 `mapInit` and `mapUpdate` as well as `map` are not what I'm looking for. While they probably can be (ab)used via side effects that doesn't seem to be a good solution (if that's what you are suggesting)

**Comment by et1975** [comment]
I don't know enough about your context to judge what's good, just thought
I'd point out that we have those.

**Comment by et1975** [comment]
Published v4 alpha with these accessors. I'll try to release the rest of the packages later in the week.

**Comment by bender2k14** [comment]
I don't see this code change anywhere.  What branch is it in?

**Comment by et1975** [comment]
just pushed to `master`.
