### ISSUE TITLE
v5 release scope

### ISSUE THREAD

**Issue by et1975** [elmish/elmish#194]
I've branched for v3 support and now the `master` is for experimental development.

So far I have (crossed out items will go into v4 as previously planned):
- [x] ~handle initialization command errors and handle each command error individually (instead of per-message)~
- [x] ~termination - affects elmish core and pretty much everything downstream~
- [ ] replace aliases (`Cmd` and `Sub`) with single-case DUs
- [ ] `lazyView` and the React/native root redesign using functional components.
- [ ] Subscriptions redesign (#183)

Up for discussion:
- Debugger switch to a fork or F# impl of the remotedev tools client.
- CE and supporting bits for composing the programs.
- potential split of React and React native (https://github.com/elmish/react/issues/43)

CC @MangelMaxime @alfonsogarciacaro @cmeeren @bender2k14 @matthid ?

**Comment by matthid** [comment]
Maybe even get rid of the remotedev dependency, it's only a couple of lines of code?

**Comment by et1975** [comment]
@matthid I'd love to have pure f# client, but are you sure it's just a couple of lines? The JS lib supports remote (needed for ReactNative) as well the plugin backends.

**Comment by et1975** [comment]
Released first alphas of the core, browser, react and debugger. @MangelMaxime think you could do the HMR?

**Comment by matthid** [comment]
>  I'd love to have pure f# client, but are you sure it's just a couple of lines? 

@et1975 It's basically just 157 lines see https://github.com/matthid/remotedev/blob/master/src/devTools.js

**Comment by et1975** [comment]
> > * Debugger switch to a fork of the remotedev tools.
> What's this? Anything that impacts end users or Elmish.WPF?
> 
Debugger is currently useless for .NET apps and changes here wouldn't affect WPF, unless we implement pure F# client, in which case it would make it possible for WPF to use existing remotedev server and UIs to collect and manage the events and state. Hope @matthid can talk about his proposed fork of the JS lib we currently use.

> > * CE and supporting bits for composing the programs.
> 
> Never heard of that. What will the CEs enable/simplify, and how?
>
The long standing issue we have is that composing the `Program` can be tricky in terms of ordering it just right and the clever workaround we have for HMR makes it difficult for 3rd parties to alter some behaviors (like `syncDispatch`) while preserving others (like HMR). I have an idea based on Free Monad to take all the various Program modifiers and reorder them according to self-declared order of each modifier. The benefit for library authors - easier/better composition, for the user - don't need to worry about plugging it in correct order.

> > * Maybe ringbuffer that doesn't require synchronization? Auto-growth will have to be traded for fixed size and result in backpressure, but maybe it's a good thing
> 
> I'm very fuzzy on these terms. Ringbuffer sounds like internal stuff, but backpressure sounds like it might impact end users. Will it, and how? What will the benefits be?

Typical RingBuffer is a thread-safe datastructure that aims to implement lock-free exchange between producer and consumer. The implementation I wrote is not thread-safe, hence the need for `syncDispatch` to govern the access to it. The proposed change might impact the end-user, but I think it can be mitigated by making the size configurable. The benefit here is elimination of the need for synchronization and existing `syncDispatch` mechanism can take on the narrower purpose, like rendering on the UI thread.

> > * I still want to see `lazyView` situation improved for React. Maybe take the `key` explicitly, even though it would be a breaking change?
> 
> Question to get a discussion going: With `memo` support in Fable.React, what is `lazyView` actually needed for?

I haven't used `memo`, so I could be wrong, but I think the `lazy` wins over eager view construction, as in `lazy` won't even call your view function if the model is the same, while `memo` needs to have its children constructed regardless wether or not it will actually render them. However it looses to `memo` once rendering takes place due to harder diff reconciliation React has to do due to the lack of `key` on the lazy element.

**Comment by et1975** [comment]
@matthid the devil is in the details, but yeah, I'd love to have pure F# impl 👍

**Comment by cmeeren** [comment]
> The proposed change might impact the end-user

How?

---

Re. memo vs. lazy: There was a previous discussion here: https://github.com/fable-compiler/fable-react/issues/138

**Comment by et1975** [comment]
> > The proposed change might impact the end-user
> 
> How?
> 
The fixed size means that when consumer can't keep up with producer it will block the producer at some point. It's a bounded queue situation, but will the end-user notice? Depends on how they produce the events. Conversely, unbounded queue might be hiding an issue, so... it's a trade-off?

**Comment by cmeeren** [comment]
> The fixed size means that when consumer can't keep up with producer it will block the producer at some point.

I guess my main concern is, will this lead to a signature change? E.g. `dispatch` returning `bool` indicating whether the dispatch succeeded or was blocked, and now we have to consider that every time we dispatch?

Also, how is Elm handling this?

**Comment by et1975** [comment]
blocking a producer means the `dispatch` won't return until a free slot becomes available in the buffer. There's no signature change or data loss, but the app might lock up. 
I don't know how Elm implements this, but I doubt that it uses bound queues as threading is never an issue in the only runtime it targets, so it wouldn't gain anything by keeping the buffer reference stable.
Regardless, the more I talk about it the more I'm inclined it keep it as is.

**Comment by cmeeren** [comment]
> the more I talk about it the more I'm inclined it keep it as is.

Yes, based on what you say it seems that the current behaviour is not obviously broken, and no users have complained yet.

**Comment by MangelMaxime** [comment]
>  @MangelMaxime think you could do the HMR?

@et1975 Yes, I will see to release an alpha version for the HMR package.

> > > * Debugger switch to a fork of the remotedev tools.
> > >   What's this? Anything that impacts end users or Elmish.WPF?
> 
> Debugger is currently useless for .NET apps and changes here wouldn't affect WPF, unless we implement pure F# client, in which case it would make it possible for WPF to use existing remotedev server and UIs to collect and manage the events and state. Hope @matthid can talk about his proposed fork of the JS lib we currently use.

I would love to see a debugger implemented in pure F#, I will give it a try and report on it when I have something to share.

**Comment by MangelMaxime** [comment]
@et1975 I just released an alpha version of the HMR package.

**Comment by bender2k14** [comment]
What about support for structured logging?

**Comment by et1975** [comment]
To help everyone understand the logging request better can you formulate
that as a story?

**Comment by bender2k14** [comment]
Sure.  I have two other potential improvements related to logging.  I just wrote all three down in #196.

**Comment by et1975** [comment]
Started on replacing aliases (`Cmd`, `Dispatch`,`Sub`) with single-case DUs - something I was considering for a long time, so hopefully not too much surprise to everyone. The goal is to make signature mismatch troubleshooting easier - aliases hide what the actual signature is.

**Comment by et1975** [comment]
I could use some help reimplementing the React/native root and the `lazyView` with functional components, if no one steps forward it's just going to take much longer to release v4.

**Comment by alfonsogarciacaro** [comment]
> I could use some help reimplementing the React/native root and the lazyView with functional components

@et1975 This is going to be tricky because the `React.memo` API used to memoize functional components requires you to keep a cached reference of the memoized component somewhere, which means you cannot call `lazyView` within another function as it is now (this would recreate the component every time, rendering memoization useless). Besides, it causes problems with F# generics.

![image](https://user-images.githubusercontent.com/8275461/84615669-97d0e080-af04-11ea-914e-3993cd98d17d.png)

We tried to solve this in Fable.React 6 using a hidden cache. But [it's causing other problems](https://github.com/fable-compiler/fable-react/issues/194#issuecomment-623531055), especially with helper functions like `lazyView`. So I'd recommend staying with class components for now.

**Comment by et1975** [comment]
@alfonsogarciacaro thanks for looking into this (again)! I thought functional/memo might be the means to an end, but if that doesn't fit, then I'm looking for other options...

**Comment by TysonMN** [comment]
What was the reason for upgrading to FSharp.Core?
https://github.com/elmish/elmish/commit/62a89382a57a8fe9e0d88fdb17ac38b78e72c39e#diff-016de9c10c0a952036856884878c35cfR15-R17

**Comment by TysonMN** [comment]
Suppose `update` throws an exception.
- In `v3.x`, this exception is caught and communited for the Elmish error logger
https://github.com/elmish/elmish/blob/b4304107342d8689ec9b97b2a9d2929857281a96/src/program.fs#L152-L153

- In `master`, the branch tracking `v4`, this exception goes unhandled and causes the application to crash.

Is this change intended?

**Comment by et1975** [comment]
With FSharp.Core the situation has always been "what's the maximum version the platform supports" and netstandard1.6 and .net 4.5 were holding it back. But I'm not using anything from FSharp.Core 4.7, so theoretically could roll back if it's causing problems.

The exception handler - yes, I need to put that back.

**Comment by TysonMN** [comment]
I was trying to test Elmish.WPF on the `elmish/master` but couldn't build because of that change and the fact that [Elmish.WPF updates the version of `FSharp.Core` to be `4.6.2`](https://github.com/elmish/Elmish.WPF/blob/9222c08ff30682719969a241ee063acab5afd923/src/Elmish.WPF/Elmish.WPF.fsproj#L50).

I don't think this is a real problem though.
