### ISSUE TITLE
Change `ofSub` singature to take the exception handler

### ISSUE THREAD

**Issue by bender2k14** [elmish/elmish#195]
I think it would be better if lines 150 and 151 were swapped.
https://github.com/elmish/elmish/blob/12648f57092ac6c3dca383e1c25995882a646447/src/program.fs#L147-L153

Specifically, if the call to `program.setState` succeeded (i.e. did not throw an exception), then I think mutating `state` by assigning it the new `model` should be next.  Otherwise, an exception thrown from a command (which is demonstrated in #186) would cause the view and the Elmish model to become out of sync.

In https://github.com/elmish/elmish/issues/186#issuecomment-524461533, I said:
> I agree that having a last line of defense is a good thing and that expected exceptions should be handled by emitting a message.  The exceptions that I have in mind are the unintended ones, and I am considering what Elmish could do to make applications built on it as robust as possible.

I hope that creating this issue will lead to improved robustness for applications built using Elmish.

**Comment by et1975** [comment]
I think it could be argued either way, the exception states that we failed
to process the message, the fact that new ui has been rendered is the least
interesting thing to me since the view is ephemeral.
Maybe executing the commands before doing any thing else would be better
though.

**Comment by bender2k14** [comment]
> ...the fact that new ui has been rendered is the least
interesting thing to me since the view is ephemeral.

I disagree.  Buttons are enabled or disabled based on the state of the model.  If the Elmish model and view are out of sync, then it could be possible to click on a button that would be disabled if the viewed matched the model Elmish has cached in `state`.

This is what I mean by making Elmish more robust.  Sure, the downstream programmers should not have let an exception escape the execution of a command, but then Elmish is making the situation worse by allowing buttons to be clicked when they should be disabled.

If any of this is unclear, I could create a branch that demonstrates this behavior.

> Maybe executing the commands before doing any thing else would be better though.

That would be one way to keep the view and Elmish model in sync.  I will think about which order makes more sense to me (executing commands then updating the view or vise versa).

Does anyone know what order Elm uses?

**Comment by et1975** [comment]
Elm doesn't have exceptions.

Regardless, I'd like all elmish contributors to embrace and promote the
idea that all exceptions should be handled in userland instead of relying
on elmish. If you own a library on top of elmish and are
overriding/implementing any behavior you should handle the exceptions,
ideally surfacing the handler to the user.

**Comment by bender2k14** [comment]
> Elm doesn't have exceptions.

Do you mean that [programs written in Elm are unable to catch or throw exceptions](https://quanttype.net/posts/2016-03-22-runtime-exceptions-in-elm.html)?

I see that as unrelated to my question.  Elm is purely functional, which means that programs written in Elm must be pure.  However, an (or the only?) implementation of Elm is certainly impure.

In the same way, an implementation of Elm could also have exception handling.  As such, I think my question is still unanswered.

Nonetheless, let's run with the idea that "Elm doesn't have exceptions" for a moment.  How about we make Elmish more like Elm in this way by wrapping commands created with `Cmd.ofSum` with try-catch-log-swallow in an attempt to replicate this behavior of "no exceptions"?  That is essentially what I was asking about in #186, but at the time, I got the impression that you didn't care about exceptions very much.

> I'd like all elmish contributors to embrace and promote the idea that all exceptions should be handled in userland instead of relying on elmish. If you own a library on top of elmish and are overriding/implementing any behavior you should handle the exceptions, ideally surfacing the handler to the user.

I would also like that.  My intention is to make Elmish as predictable as possible.

Let me try another approach.  In the [Elmish documentation](https://elmish.github.io/elmish/), it says
> - View
>   This is a pure function that produces a new UI layout/content given the current state, defined as an F# function that uses a renderer (such as React) to declaratively build a UI.

I do not think that this describes the current implementation.  Instead, the think a description of the current implementation would be
> - View
>   This is a pure function that produces a new UI layout/content given the ~current~ next state, defined as an F# function that uses a renderer (such as React) to declaratively build a UI.

In order to match the current documentation, I think the implementation should be
```F#
148  let (model',cmd') = program.update msg state
149  state <- model'
150  program.setState state syncDispatch
151  cmd' |> Cmd.exec syncDispatch
```

I opened this issue with the suggestion of moving `state <- model'` up by one line.  Now I have just given an argument for why it should be moved up two lines.

More generally, what I think I am really after is having
- `state <- model'` and
- `program.setState state syncDispatch`

appear sequentially.  Moving `state <- model'` up either one or two lines from its current position achieves that goal.

**Comment by et1975** [comment]
From view perspective whether the state is stored anywhere is irrelevant - it's current as the last `update` call produced it, one is implementation detail and another one is conceptual, let's not couple the two. 

The problem with storing the current and then going "oops, something went wrong" is that it's going to go into the next update, and to me that's an overriding concern and absolutely should not be allowed.

`Cmd.ofSub` is indeed the only `Cmd` in the core that could throw, but:
-  it doesn't produce any message on its own.
-  wrapping it in a handler that does will map all errors into the same message, which might be too restrictive for something that can emit at any time for any reason whatsoever.

I feel like it's one of those extension points that should handle the exception on itsown.
Besides, we already have a big Subscriptions revamp suggestion that I'd rather see happen (#183).

**Comment by bender2k14** [comment]
> From view perspective whether the state is stored anywhere is irrelevant - it's current as the last `update` call produced it, one is implementation detail and another one is conceptual, let's not couple the two.

Yes, I agree with that now.

> The problem with storing the current and then going "oops, something went wrong" is that it's going to go into the next update, and to me that's an overriding concern and absolutely should not be allowed.

You have described this at a very high level.  When the only thing we know is "oops, something went wrong", then yes, I agree that mutating the model seems like the wrong thing to do.

> `Cmd.ofSub` is indeed the only `Cmd` in the core that could throw...

Maybe this issue can be viewed as a kind of duplicate of #186.  Both are about something that I find unexpected that happens as a result of `Cmd.ofSub` allowing exceptions to go unhandled.

> ...wrapping [`Cmd.ofSub`] in a handler that [produces messages of its own] will map all errors into the same message, which might be too restrictive for something that can emit at any time for any reason whatsoever.

I am definitely not suggesting that we do this.  Instead, I think a good choice would be to make the behavior of `Cmd.ofSub` more like `OfFunc.perform`:
https://github.com/elmish/elmish/blob/12648f57092ac6c3dca383e1c25995882a646447/src/cmd.fs#L56-L65

So that would change...
https://github.com/elmish/elmish/blob/12648f57092ac6c3dca383e1c25995882a646447/src/cmd.fs#L40-L42

...into
```F#
let ofSub (sub: Sub<'msg>) : Cmd<'msg> =
    let bind dispatch =
        try
            sub dispatch
        with x ->
            ()
    [bind]
```

Does this change seem reasonable?

**Comment by et1975** [comment]
Here's the my stance on errors and logging that drives most of the decision-making here: logging an error is a form of data loss. I don't care how good your sink is, if elmish has cought it the user has lost. 
From that perspective swalling an exception in `perform` is something the user has to opt into, I'm not interested exception swalling for the sake of "robustness".

**Comment by bender2k14** [comment]
Ok.  Let's try to turn a loss into a win.

The current behavior of `Cmd.ofSub` allows the user to lose because any exception of theirs be caught and logged by Elmish here
https://github.com/elmish/elmish/blob/12648f57092ac6c3dca383e1c25995882a646447/src/program.fs#L147-L153

How about we change `Cmd.ofSub` to take an `onException` callback?

```F#
let ofSub (sub: Sub<'msg>) (onException: exn -> unit) : Cmd<'msg> =
    let bind dispatch =
        try
            sub dispatch
        with e ->
            onException e
    [bind]
```

That would now be a win for the user.

**Comment by et1975** [comment]
@MangelMaxime what do you think? 
There's probably a lot of code that would break if we change `ofSub` signature now, but adding `ofSubAttempt` doesn't feel worthwhile, considering user's who do have exceptions would already have the try/with in the sub.

**Comment by et1975** [comment]
Actually, maybe this change is going to be a small fry after all - I'm going forward with changing the type aliases to Single-case DUs!

**Comment by et1975** [comment]
Closing, I think I'm going to try implementing #183 instead.

**Comment by TysonMN** [comment]
Are #183 and this issue mutually exclusive?

**Comment by et1975** [comment]
We'll see, but in the meantime your suggestion is already implemented in the master.

**Comment by MangelMaxime** [comment]
@et1975 Personally, I am ok with breaking change in a major version especially if it forces the user to handle failing case etc.

We don't often make breaking changes in Elmish so I think it is ok to take the opportunity of Elmish v4 to clean everything we have in the backlog.

**Comment by TysonMN** [comment]
> Here's the my stance on errors and logging that drives most of the decision-making here: logging an error is a form of data loss. I don't care how good your sink is, if elmish has cought it the user has lost.
> From that perspective swalling an exception in `perform` is something the user has to opt into, I'm not interested exception swalling for the sake of "robustness".

A related issue is the canceling an asynchronous computation.  I don't see Elmish asking the user for a cancelation callback.  This might represent another loss for Elmish since it is the one holding onto a canceled `Async<_>` and nowhere to turn.
