### ISSUE TITLE
Catch-log-swallow exception from initial command

### ISSUE THREAD

**Issue by bender2k14** [elmish/elmish#197]
An exception thrown from a command returned from `init` or from `withSubscription` is an unhandled exception, which causes the program to crash.  (Side note: I think these two ways to create a command are isomorphic.  See https://github.com/elmish/elmish/issues/183#issuecomment-526826760.)

I would prefer if this exception were caught, logged, and execution continued without crashing the program.  The behavior that I prefer is the actual behavior if the command in question is returned from `update` instead of from `init` or `withSubscription`.

**Comment by et1975** [comment]
Yeah, i need to revisit how initalization happens. The discrepancy is
historical, but now that dispatch doesn't run async i think I can route it
thorough that.

**Comment by et1975** [comment]
Done in the master, will be released as part of 4.0.
