### ISSUE TITLE
Rename Fable.Elmish.fsproj to Elmish.fsproj?

### ISSUE THREAD

**Issue by bender2k14** [elmish/elmish#198]
Can we rename `Fable.Elmish.fsproj` to `Elmish.fsproj`?

**Comment by et1975** [comment]
There's elmish project in netstandard and I consider prefixing projects
targeting Fable a good thing.

**Comment by bender2k14** [comment]
> There's elmish project in netstandard...

I don't understand this.  Can you elaborate?

**Comment by et1975** [comment]
There are two projects, one for .net, one for fable.

**Comment by bender2k14** [comment]
Oh!  I never noticed that there were two `fsproj` files:
- [netstandard/Elmish.fsproj](https://github.com/elmish/elmish/blob/v3.x/netstandard/Elmish.fsproj) and
- [src/Fable.Elmish.fsproj](https://github.com/elmish/elmish/blob/v3.x/src/Fable.Elmish.fsproj)

Nevermind, `Fable.Elmish.fsproj` is a great name for that file.
