### ISSUE TITLE
Parallel structure between fsproj files

### ISSUE THREAD

**Issue by bender2k14** [elmish/elmish#199]
There are two non-test `fsproj` files:
- [netstandard/Elmish.fsproj](https://github.com/elmish/elmish/blob/v3.x/netstandard/Elmish.fsproj) and
- [src/Fable.Elmish.fsproj](https://github.com/elmish/elmish/blob/v3.x/src/Fable.Elmish.fsproj).

(Before I realized that, I put out a misguided request in #198.)

Can we get some parallel structure between these files and their proximity to the `fs` files they reference?

For example, how about this organization?

- src
   - NetStandard
      - NetStandard.Elmish.fsproj
      - netfx.props
      - paket.references
   - Fable
      - Fable.Elmish.fsproj
      - paket.references
   - cmd.fs
   - prelude.fs
   - program.fs
   - ring.fs

**Comment by et1975** [comment]
Thanks, but I happen to like the current directory structure - it is quite common and dates back to the days .NET developers had to build x86/x64 off the same sources.

**Comment by bender2k14** [comment]
Why do you consider `Fable.Elmish.fsproj` a "source" file (because its directory path includes `src`) but you do not consider `Elmish.fsproj` a "source" file (because its directory path does _not_ include `src`)?
