### ISSUE TITLE
Shouldn't we use value tuples for init and update?

### ISSUE THREAD

**Issue by OnurGumus** [elmish/elmish#200]
This is more like a question but shouldn't we use struct tuples for the init and update function in order to avoid allocation?

**Comment by forki** [comment]
Elmish is primarily used in fable compilation to Javascript. So it would probably make no difference at all.

**Comment by OnurGumus** [comment]
@forki that's not true. There is bolero using elmish and Xelmish for xna, WPF, XAMARIN, Gui Terminal

**Comment by forki** [comment]
And there is evidence that value tuples would improve perf? Init is called once so that's clearly not important at all. And even update is not called in a tight loop, so I assume it would not change anything.

**Comment by OnurGumus** [comment]
@forki , think of applications like Xelmish (elmish for monogame/xamarin), which calls update for X frames per second. Think of games. This is a low hanging fruit. You are right it is not that beneficial either, but there is no harm for doing it. All you have to do add an overload to mkProgram such as mkProgramWithValueTuple. Why not benefit it if it is free?

**Comment by forki** [comment]
It's not a performance problem until we show that it is one. Can you try to
use a profiler? I personally am convinced this will be no difference at
all. Like absolutely zero. So please go ahead proof me wrong. It would make
a nice case study.

Onur Gumus <notifications@github.com> schrieb am Sa., 30. Nov. 2019, 07:45:

**Comment by OnurGumus** [comment]
@forki  I know same conversation goes on with twitter but for the sake of completeness I post the same
https://gist.github.com/OnurGumus/8e81ee89b385e10be38f24f98020ecad
Simply delete 3 struct keywords and ref tuples are 2 x slower.

**Comment by forki** [comment]
That is not the same as replacing it in elmish. Not remotely related.

Onur Gumus <notifications@github.com> schrieb am Sa., 30. Nov. 2019, 10:34:

**Comment by OnurGumus** [comment]
Yes since elmish itself will introduce a delay which will probably surpass the delay comes from my example. But still it shows a nice impact of using ref tuples over value tuples.

**Comment by forki** [comment]
It only shows it's faster in that concrete scenario. It's slower in others.

Onur Gumus <notifications@github.com> schrieb am Sa., 30. Nov. 2019, 10:46:

**Comment by bender2k14** [comment]
> There is bolero using elmish and Xelmish for xna, WPF, XAMARIN, Gui Terminal

I recall reading somewhere a much shorter list of projects using Elmish.  IIRC, the list only had two examples.

Does anyone remember where this list is?

I would like to add to this list.

**Comment by et1975** [comment]
Onur, are you comparing curried arguments to tuples? I could see struct
tuples doing better in frequent updates than heap tuples (for some `msg and
`model types!), but not better than curried arguments. In any case, this
would have to be very evidence-driven, I don't see it changing otherwise.

**Comment by OnurGumus** [comment]
@et1975, I was referring to the return value of update.

**Comment by et1975** [comment]
ah, I see what you mean, thanks for the idea!
Maybe we could make this version available in a separate package for those that need it, so as not to break everyone's app needlessly.

**Comment by et1975** [comment]
@OnurGumus I don't have the capacity to maintain another version of elmish and I suspect that struct tuples on return will not be the one or the only change for high-throughput application. I think fixed length ringbuffer and lock-free access to it might be an area of high impact. Commands that don't allocate lists all the time as well.
I'd suggest forking the elmish repo and starting from there with a profiler. Let me know if you want to give it go yourself and if you need any help getting started, but I'm going to close this request.
