### ISSUE TITLE
Some Dispatched Messages go missing

### ISSUE THREAD

**Issue by matthid** [elmish/elmish#201]
### Description

I assume the problem is that the ringbuffer runs out in some scenarios for us:

https://github.com/elmish/elmish/blob/12648f57092ac6c3dca383e1c25995882a646447/src/program.fs#L136

### Expected and actual results

We expect that all dispatched messages are handled eventually to have a consistent state

Currently some messages seem to get lost.

### Description

I understand that the buffer needs to have some limitation, but this default behavior is really dangerous, because it does not reflect user expectations. We should at least warn the user if the buffer is full and give other options (like an unlimited buffer or increasing buffer size).

In a perfect world we could set "critical" and "non"-critical messages. Because I feel at dispatching (or globally) you know which messages can be thrown away and which can't because of program logic.

We are still investigating, but I think the above is the error and it should be easy to reproduce by dispatching 11 messages.

### Related information 

* elmish version: v3
* fable-compiler version: 2.4.11
* fable-core version: 3.1.4
* Operating system: Win10

**Comment by Zaid-Ajaj** [comment]
@matthid Assuming you using Elmish with React, are using `Program.withReactSynchronous` or `Program.withReactBatched`? if you are using the latter, try switching to `Program.withReactSynchronous`. 

Asmall sample to reproduce the issue would be great to have

**Comment by bender2k14** [comment]
I previously reviewed the `RingBuffer` code, and my conclusion was that it is bug free.   It is not thread safe though, so it is necessary to ensure that Elmish dispatch loop is only executed by a single thread.  (There is an GitHub related to this.  I will edit my comment later to link to that issue.)

The parameter `10` (that is bound to `size` in the code below) is just the initial size of the underlying array.

https://github.com/elmish/elmish/blob/12648f57092ac6c3dca383e1c25995882a646447/src/ring.fs#L18

When the 11th message is pushed without popping any in the meantime, then a new array of length `10 * 2 = 20` is created to hold the 11 messages.

https://github.com/elmish/elmish/blob/12648f57092ac6c3dca383e1c25995882a646447/src/ring.fs#L44

**Comment by matthid** [comment]
We switched to `withReactSynchronous` because of performance problems.
But looking at the code why would that matter, can you elaborate?

> Asmall sample to reproduce the issue would be great to have

I tried to reproduce in the repl but I cannot use `withReactBatched` there and in fact I cannot easily reproduce the problem, so maybe we are missing something else here :)

**Comment by matthid** [comment]
> I previously reviewed the RingBuffer code, and my conclusion was that it is bug free. It is not thread safe though, so it is necessary to ensure that Elmish dispatch loop is only executed by a single thread. 

But there is only a single thread in JavaScript, so there shouldn't be a problem or do you mean something else?

**Comment by matthid** [comment]
We are still investigating but I think the error is probably somewhere else

**Comment by bender2k14** [comment]
> But there is only a single thread in JavaScript, so there shouldn't be a problem or do you mean something else?

I only use Elmish via [Elmish.WPF](https://github.com/elmish/Elmish.WPF), and it executes the dispatch loop on the UI thread.  If JavaScript only has a single thread, then the fact that `RingBuffer` is not thread safe shouldn't be a problem.

> We are still investigating but I think the error is probably somewhere else

That is where I would put my money as well.  Good luck finding your problem! :)

**Comment by et1975** [comment]
There was a bug in the early v3 release, please make sure you are running
latest!
