### ISSUE TITLE
Documentation: Parent-child composition and user interaction

### ISSUE THREAD

**Issue by mjarosie** [elmish/elmish#202]
Hi,

it's more of a topic about documentation improvement. I'd be willing to contribute, but my understanding of both Elmish and model-view-update architecture is still quite limited, so I thought I'd share my view so that the documentation could be improved which would (hopefully) benefit the project.

Bit of a background - I've just started learning functional programming and F#, I've never written a single line of Elm, but my first impression of the MVU approach is very positive! I'm describing my experience with the documentation from the point of view of someone who sees it for the first time. 

I went through the example of [parent-child composition](https://elmish.github.io/elmish/parent-child.html) and I've noticed that its content doesn't correspond to the UML sequence diagram on the [main page of the documentation](https://elmish.github.io/elmish/#Parent-child-composition-and-user-interaction) which is quite confusing. I think consolidating these two descriptions would make it way much clearer. I could modify either the diagram or the example, but because of my limited knowledge, I don't know which one of these two is more descriptive.

[I've implemented](https://github.com/mjarosie/elmish-parent-child-composition-demo/blob/master/src/App.fs) the logic described in [parent-child composition](https://elmish.github.io/elmish/parent-child.html) page and when going to http://localhost:8080 just the initial state of the application is being logged (after looking into it for a while I understand it's because messages are not being dispatched from the UI as in the example described on the main page of the documentation). I believe the interaction with the UI is not described because, as the documentation mentions, elmish is UI agnostic, but I'm wondering if maybe it should be framed more explicitly? For example, mentioning something along these lines at the end of [parent-child example](https://elmish.github.io/elmish/parent-child.html):

"To see the model working, implement the UI which dispatches `Counter.Msg.Increment` and `Counter.Msg.Decrement` messages so that the application can react to it."

(As I've mentioned, I don't have much experience with MVU so not sure if I described it correctly).

Alternative solution would be to refer to some sample implementation (something similar to other samples, such as [sample-react-counter](https://github.com/elmish/sample-react-counter)).

Also - I've looked at [where the UML sequence diagram is defined](https://github.com/elmish/elmish/blob/v3.x/docs/content/parent-child.wsd) and I've noticed that it's "cut" - the second part of the diagram where the user is interacting with the browser (and which is described in text [under the schema](https://elmish.github.io/elmish/#Parent-child-composition-and-user-interaction)) is not shown. Even though the PlantUML documentation [says it works](https://plantuml.com/sequence-diagram#45d7d5b32d17a0f9), I don't think that any browser will be able to render the second page (unless I'm missing something?). I think the best solution would be to split this schema into two files:

- [UI initialisation](http://www.plantuml.com/plantuml/uml/VP7HIW9158RlzoaEUb51YaLq4I6ADmKPWUXUdtKFUcZcp39xHf-fr-Z9cb4s9jGkz_---NyEEsaLlGPhYYlu_e85LTWgey27y-hWVdJtU0kH6LwJj5H3a9ey8CmyeVAEOEQiTTB2LDLp5PIT3DwTf9Zycj4C5blqD3NyIV0m7C6hA7d19AA1jsFniC2WJeAjo4FlkHfVzszwHODUUSqDYiAoZQI_txBIdxpnRkFHdaDpP1coi3AQkQl90BOmvylkZcb_S5ONbT3Kg7IGbkUaakiDwSbgoVOVkzijLvUbRBdyNIwwwmVZTDWJvBj5J18eJq2PGFTaVwZFNaHmh8tG8iiHvKiho4dyJ2ifpBlA67VoYzhavTrTclMcNzp5HJ4XgOCrFm00)
- [interaction with the user](http://www.plantuml.com/plantuml/uml/TP1DYjj048NtVOfYPf4nZCqaX2nC6CPuaq0K0aRIkgGkxCBz8xfBzfboZPmiKYjIPCRQllTLlLVr5WM3jDQe3_3dDnoemYYC3dxv81u-lNpyyWoTPxWc5qb3wpG5GDW7Gk4BmTvRwrs4dKZWgXNsRltJkrwcK3EQzU64WNQ6pmIVDo_mtGa5Xps81duCYpSAM_6kjHK5UFXQlJuzhXvKWq6uvWQTG1uxv_5wOg4RlGd-6D3Uip9ajs77mcWohya0HiXucRqmNHDJB29jer4eGVazg6Hz97cNMh9TfgVSibY6PidbbAnKUilwjH_TmjvmVLPbqGjPiUrUNGV2I2hhfV5LMtWQLcRnE24hzSzDi_bz1YooIpUfB4-fEVnFWUimaVooyyTDGtCzzv-XzjQYqwkqQLvkmgUm6JmlsLqyBrHCRxZfqSaZ_4riucPne_f6JhVM_0K0)

This will make both pages visible : )

**Comment by Zaid-Ajaj** [comment]
Hi @mjarosie, did you happen to check out [The Elmish Book](https://zaid-ajaj.github.io/the-elmish-book)? It goes quite into detail on the architecture, specifically speaking [Chapter 4 - Composing Larger Applications](https://zaid-ajaj.github.io/the-elmish-book/#/chapters/scaling/) dives into parent-child communication techniques and the different composition models with practical examples

**Comment by et1975** [comment]
@mjarosie Thanks for pointing out the problem with the diagram, a PR with the fix would be appreciated!

**Comment by mjarosie** [comment]
> 
> 
> Hi @mjarosie, did you happen to check out [The Elmish Book](https://zaid-ajaj.github.io/the-elmish-book)? It goes quite into detail on the architecture, specifically speaking [Chapter 4 - Composing Larger Applications](https://zaid-ajaj.github.io/the-elmish-book/#/chapters/scaling/) dives into parent-child communication techniques and the different composition models with practical examples

Thanks Zaid, I just skimmed through your book, it looks like a great introductory resource! I didn't stumble upon it before, should this book be mentioned somewhere in the documentation of elmish itself so that it's easier to find for new starters like me? Elmish examples subpages could also refer to the chapters of the book for further explanation, I think that'd be a great help for newcomers!


> 
> 
> @mjarosie Thanks for pointing out the problem with the diagram, a PR with the fix would be appreciated!

Sure, I'll fill it in this weekend! : )

**Comment by mjarosie** [comment]
@et1975 I've filled in the PR, I'm not sure if there's anything else that needs to be done to update the github.io page itself. Could you take a look please? Thanks!

**Comment by et1975** [comment]
Thanks, you're good, I'll publish this tonight.

**Comment by et1975** [comment]
Something is very wrong with FSharp.Formatting again, but with a bit of elbow grease I published your update.
Thanks again!
